# -*- coding: utf-8 -*-
"""Varzharan — Elementary Mathematics syllabi, Grades 1-5."""

BAND = "Elementary Mathematics"
BAND_HY = "Տարրական մաթեմատիկա"

COURSES = []

# ---------------------------------------------------------------- GRADE 1
COURSES.append({
    "code": "MTH-G1",
    "title_en": "Grade 1 Mathematics",
    "title_hy": "Մաթեմատիկա — 1-ին դասարան",
    "band": BAND, "band_hy": BAND_HY,
    "grade_label": "Grade 1 · typical age 6–7",
    "hours": "60–72 instructional hours (approx. 60 lessons)",
    "prereq": "Counts orally to at least 20; recognizes written numerals 0–10; can compare small groups by size.",
    "next": "Grade 2 Mathematics (MTH-G2)",
    "description": (
        "Grade 1 is the year in which a child stops counting and begins to reason about number. "
        "The course builds a secure understanding of quantity to 120, develops fluent addition and "
        "subtraction within 20 through strategy rather than memorization, and introduces place value as "
        "the organizing idea that will carry the student through all of elementary arithmetic. Students "
        "also learn to measure by iterating a unit, to tell time, to work with coins, and to describe and "
        "compose two- and three-dimensional shapes."
    ),
    "philosophy": (
        "At Վարժարան, Grade 1 is taught concretely before it is taught symbolically. Every new idea is met "
        "first with objects or drawings, then with a diagram, and only then with an equation — the "
        "concrete–pictorial–abstract sequence. The teacher's central job this year is not to get correct "
        "answers but to get correct explanations: a first-grader who can say why 8 + 5 is 13 is far better "
        "positioned than one who has memorized it. Lessons are 30–45 minutes, highly interactive, and "
        "paced to the child's attention rather than to the clock."
    ),
    "readiness": [
        ("Counts to 20 without skipping or repeating",
         "Rote counting is the foundation for counting-on strategies; if absent, begin with Unit 1 extended."),
        ("Matches a spoken number to a set of that many objects",
         "Demonstrates one-to-one correspondence and cardinality — the true prerequisite for addition."),
        ("Recognizes and writes numerals 0–10",
         "If reversals are present, treat as normal at this age; do not delay content."),
        ("Identifies which of two small groups has more",
         "Comparison language ('more', 'fewer', 'the same') precedes the symbols >, <, =."),
    ],
    "outcomes": [
        "Count, read, write, and represent whole numbers to 120, starting from any number.",
        "Add and subtract fluently within 20 using at least two reliable strategies, and within 10 from memory.",
        "Explain why an addition or subtraction strategy works, using objects, drawings, or a number line.",
        "Understand two-digit numbers as tens and ones, and compare them using >, <, and =.",
        "Add a two-digit number and a multiple of ten, and mentally find 10 more or 10 less.",
        "Solve one-step word problems of all three types (add-to, take-from, put-together/take-apart) within 20.",
        "Measure length by iterating a shorter unit, and order three objects by length.",
        "Tell and write time to the hour and half-hour on analog and digital clocks.",
        "Identify, describe, compose, and partition basic 2-D and 3-D shapes; partition into halves and fourths.",
    ],
    "units": [
        {"n": 1, "name_en": "Number Sense to 20", "name_hy": "Թվային պատկերացում մինչև 20",
         "lessons": "7–8 lessons",
         "topics": ["Counting forward and backward from any number to 20", "One-to-one correspondence and cardinality",
                    "Subitizing: recognizing 1–6 without counting", "Ten-frames and the anchor numbers 5 and 10",
                    "Ordinal position: first through tenth", "Comparing quantities: more, fewer, equal",
                    "Writing numerals 0–20 and matching numeral to quantity"],
         "objectives": ["Count forward to 20 beginning at any given number, not only at 1.",
                        "State how many objects are in a set without recounting (cardinality).",
                        "Instantly recognize arrangements of up to 6 objects without counting.",
                        "Decompose numbers to 10 in every way (e.g., 7 as 6+1, 5+2, 4+3) using a ten-frame.",
                        "Compare two sets and justify which is greater using matching, not counting."],
         "mastery": ["Counts on from a given number in 4 of 5 trials without restarting at 1.",
                     "Names 'how many' after a single count, with no recount, in 4 of 5 trials.",
                     "Produces all pairs summing to 10 within 60 seconds using a ten-frame."],
         "misconceptions": [
             ("The child recounts the set each time they are asked 'how many?'",
              "Cardinality is not yet established. Cover the set after counting and ask again; use the 'hiding game' daily until the last count word is understood as the total."),
             ("The child counts every object starting from one when adding.",
              "Introduce counting-on explicitly: put the larger number 'in your head' and count up the smaller on fingers. Do not allow the strategy to be discovered by chance."),
         ],
         "note": "This unit sets the tone for the year. Resist the urge to move quickly — a student who leaves this unit without cardinality and subitizing will compensate with finger-counting for years."},

        {"n": 2, "name_en": "Addition and Subtraction Within 10", "name_hy": "Գումարում և հանում 10-ի սահմաններում",
         "lessons": "8–9 lessons",
         "topics": ["The meaning of addition: joining and part-part-whole", "The meaning of subtraction: taking from, comparing, missing part",
                    "The symbols +, −, = and reading an equation aloud", "Counting-on from the larger addend",
                    "Number bonds and fact families", "Doubles and near-doubles to 10",
                    "The commutative property discovered, not stated", "Adding and subtracting zero"],
         "objectives": ["Represent an addition or subtraction situation with objects, a drawing, and an equation.",
                        "Use counting-on rather than counting-all for sums within 10.",
                        "Produce the full fact family from a number bond (e.g., 3, 4, 7).",
                        "Know from memory all sums of two one-digit numbers within 10.",
                        "Explain that a + b = b + a using a picture, without using the word 'commutative'."],
         "mastery": ["Recalls all facts within 10 with under 3 seconds of hesitation.",
                     "Writes both addition and both subtraction equations for a given number bond.",
                     "Uses counting-on, not counting-all, as the default strategy in observation."],
         "misconceptions": [
             ("The child reads '=' as 'the answer comes next'.",
              "This is the single most consequential misconception in elementary mathematics. Deliberately write 7 = 3 + 4 and 3 + 4 = 2 + 5. Ask 'is this true?' rather than 'what is the answer?'"),
             ("Subtraction is understood only as 'take away'.",
              "Teach all three meanings from the start — take-away, comparison, and missing addend — or the child will be unable to solve 3 + ? = 8."),
         ],
         "note": "Fluency here means efficient and flexible, not fast and memorized. A child who computes 6 + 3 by counting on from 6 is fluent; one who has memorized it but cannot explain it is not."},

        {"n": 3, "name_en": "Addition and Subtraction Within 20", "name_hy": "Գումարում և հանում 20-ի սահմաններում",
         "lessons": "9–10 lessons",
         "topics": ["Teen numbers as ten and some ones", "Making ten to add (8 + 5 = 8 + 2 + 3)",
                    "Doubles and doubles-plus-one within 20", "Subtracting through ten (15 − 7 = 15 − 5 − 2)",
                    "Missing-addend problems: 9 + ? = 14", "Adding three whole numbers",
                    "The associative property in service of strategy", "Relating addition and subtraction to check work"],
         "objectives": ["Decompose an addend to make a ten, and explain why this does not change the sum.",
                        "Add and subtract within 20 using a chosen strategy, and defend the choice.",
                        "Solve missing-addend equations by relating them to subtraction.",
                        "Add three one-digit numbers by first finding a pair that makes ten."],
         "mastery": ["Solves any sum within 20 in under 5 seconds using an efficient strategy.",
                     "Explains the make-ten strategy aloud with a ten-frame or number bond.",
                     "Correctly solves 8 of 10 missing-addend problems."],
         "misconceptions": [
             ("The child breaks apart the wrong addend when making ten.",
              "Always break the number that is *not* near ten. Practice deciding which addend to keep whole before computing anything."),
             ("Subtraction is performed by counting back one at a time from 15.",
              "Slow and error-prone. Model subtracting to ten first, then the remainder — the mirror of make-ten."),
         ],
         "note": "This is the highest-leverage unit of Grade 1. Fluency within 20 is the arithmetic bottleneck for Grades 2–4. Do not advance until it is secure, even if the calendar says otherwise."},

        {"n": 4, "name_en": "Place Value to 120", "name_hy": "Կարգային արժեք մինչև 120",
         "lessons": "7–8 lessons",
         "topics": ["Bundling ten ones into one ten", "Two-digit numbers as tens and ones",
                    "Reading, writing, and representing numbers to 120", "Counting by tens from any number",
                    "10 more and 10 less, mentally", "Comparing two-digit numbers with >, <, =",
                    "Adding a two-digit number and a multiple of ten", "Adding a two-digit number and a one-digit number"],
         "objectives": ["Explain that the 4 in 47 means four tens, using bundled objects.",
                        "Write any number to 120 given in words or in tens-and-ones form.",
                        "Find 10 more or 10 less than a two-digit number without counting.",
                        "Compare two two-digit numbers by reasoning about tens first, then ones."],
         "mastery": ["Represents any number to 100 with tens and ones in two different ways.",
                     "Answers '10 more than 63' in under 3 seconds.",
                     "Compares two-digit numbers correctly in 9 of 10 trials, with justification."],
         "misconceptions": [
             ("The child says 47 is 'a four and a seven'.",
              "Place value has not been constructed. Return to physical bundling — ten straws banded together — before any symbolic work."),
             ("The child says 19 is greater than 21 because 9 > 1.",
              "Compare tens first. Make this an explicit spoken routine: 'How many tens? Two tens beats one ten.'"),
         ],
         "note": "Place value is the concept that most reliably predicts later arithmetic success. Ten minutes of bundling with real objects is worth an hour of worksheets."},

        {"n": 5, "name_en": "Measurement, Time, and Money", "name_hy": "Չափում, ժամանակ և փող",
         "lessons": "6–7 lessons",
         "topics": ["Comparing and ordering objects by length", "Measuring by iterating a shorter unit end to end",
                    "Indirect comparison: if A > B and B > C, then A > C", "Telling time to the hour and half-hour",
                    "Analog and digital clock faces", "Identifying coins and their values (penny, nickel, dime, quarter)",
                    "Counting collections of like coins"],
         "objectives": ["Order three objects by length and justify using direct comparison.",
                        "Measure an object with same-size units placed with no gaps or overlaps.",
                        "Tell and write time to the half-hour on both clock types.",
                        "Identify each US coin and state its value."],
         "mastery": ["Measures accurately with no gaps or overlaps in 4 of 5 trials.",
                     "Reads half-past times correctly in 8 of 10 trials.",
                     "Names all four common coins and their values without prompting."],
         "misconceptions": [
             ("The child leaves gaps between units or overlaps them when measuring.",
              "Emphasize that measurement units must tile the object exactly. Let the child measure the same object twice, carelessly and carefully, and compare results."),
             ("The child reads 3:30 as 'four-thirty' because the hour hand is near the 4.",
              "Teach the hour hand as moving continuously between numbers; it names the hour it has *passed*, not the one it approaches."),
         ],
         "note": "Money is included because it makes place value tangible: a dime is a bundled ten. Use coins deliberately when reviewing Unit 4."},

        {"n": 6, "name_en": "Geometry and Fractions as Fair Shares", "name_hy": "Երկրաչափություն և կոտորակներ",
         "lessons": "6–7 lessons",
         "topics": ["Defining vs. non-defining attributes of shapes", "Naming 2-D shapes: triangle, rectangle, square, trapezoid, circle, hexagon",
                    "Naming 3-D shapes: cube, cone, cylinder, sphere, rectangular prism", "Composing new shapes from smaller shapes",
                    "Partitioning circles and rectangles into two and four equal shares",
                    "The language of halves, fourths, and quarters", "Understanding that more equal shares means smaller pieces"],
         "objectives": ["Distinguish attributes that define a shape (number of sides) from those that do not (color, size, orientation).",
                        "Build a larger shape from pattern-block pieces and describe the composition.",
                        "Partition a shape into two or four equal shares and name one share.",
                        "Explain why a fourth of a pizza is smaller than a half of the same pizza."],
         "mastery": ["Identifies a triangle regardless of orientation or proportion in 5 of 5 trials.",
                     "Partitions a rectangle into four equal shares and names one share correctly.",
                     "States that fourths are smaller than halves, with a drawing to justify."],
         "misconceptions": [
             ("A triangle resting on a vertex is not recognized as a triangle.",
              "Prototype thinking. Show non-standard orientations and irregular triangles from the very first lesson."),
             ("Any two pieces are called 'halves' regardless of size.",
              "Halves must be *equal* shares. Deliberately cut a paper unequally and ask whether the child wants the 'half' on the left."),
         ],
         "note": "Fair-shares language planted here is what makes Grade 3 fractions feel familiar rather than foreign. Say 'one of two equal shares' before ever writing 1/2."},
    ],
    "assessment": [
        ("Placement Assessment", "Before enrollment", "Counting, cardinality, numeral recognition, comparison; produces the initial academic profile."),
        ("Unit Check", "End of each unit · 10–15 min", "Mastery criteria for that unit only; oral and written, teacher-administered live."),
        ("Fluency Probe", "Every 3rd lesson · 3 min", "Addition/subtraction facts within 10, then within 20; tracks strategy use, not just accuracy."),
        ("Mid-Year Assessment", "After Unit 3", "Cumulative Units 1–3; triggers pacing adjustment if below 80%."),
        ("End-of-Course Assessment", "After Unit 6", "All course outcomes; determines readiness for Grade 2 placement."),
    ],
    "pacing": [
        ("Standard", "1 lesson/week, 45 min", "Full course in approximately 40–45 weeks (one academic year)."),
        ("Accelerated", "2 lessons/week, 45 min", "Full course in approximately 22–25 weeks."),
        ("Intensive / Catch-Up", "2–3 lessons/week", "Used when the placement assessment shows the student is behind grade level; 16–20 weeks."),
        ("Summer Program", "3 lessons/week, 6 weeks", "Units 1–3 only, or targeted remediation of identified gaps."),
    ],
    "homework": (
        "Grade 1 homework is short by design: 10 minutes, no more than five problems, assigned after every lesson. "
        "Its purpose is retrieval practice, not new learning — nothing is assigned that was not taught. Roughly one "
        "third of each assignment revisits earlier units so that fluency is maintained rather than lost. Parents are "
        "asked to sit nearby but not to teach; if the child is stuck for more than two minutes, the correct action is "
        "to stop and note it for the teacher."
    ),
    "milestones": [
        "Understands that the last number counted tells how many (cardinality).",
        "Knows all addition and subtraction facts within 10 from memory.",
        "Adds and subtracts fluently within 20 using the make-ten strategy.",
        "Reads, writes, and compares any number to 120.",
        "Finds 10 more or 10 less than any two-digit number mentally.",
        "Tells time to the half-hour and identifies all US coins.",
        "Partitions shapes into halves and fourths and explains why fourths are smaller.",
        "Completed Grade 1 Mathematics — ready for Grade 2.",
    ],
    "materials": [
        "Digital whiteboard with movable counters, ten-frames, and a number line to 120 (teacher-shared).",
        "Physical set at home: 100 counting objects, ten-frame cards, a set of US coins, a small ruler.",
        "Pattern blocks (physical or on-screen) for the geometry unit.",
        "Վարժարան Grade 1 problem bank — approximately 600 items tagged by unit and difficulty.",
    ],
})

# ---------------------------------------------------------------- GRADE 2
COURSES.append({
    "code": "MTH-G2",
    "title_en": "Grade 2 Mathematics",
    "title_hy": "Մաթեմատիկա — 2-րդ դասարան",
    "band": BAND, "band_hy": BAND_HY,
    "grade_label": "Grade 2 · typical age 7–8",
    "hours": "60–72 instructional hours (approx. 60 lessons)",
    "prereq": "Grade 1 Mathematics or equivalent: fluency within 20, place value to 120.",
    "next": "Grade 3 Mathematics (MTH-G3)",
    "description": (
        "Grade 2 extends place value to 1,000 and turns the strategies of Grade 1 into reliable multi-digit "
        "procedures. Students add and subtract within 100 fluently and within 1,000 with models, learn to "
        "measure with standard units and to estimate, work with equal groups and arrays as the seed of "
        "multiplication, and read and construct simple data displays. The year ends with a student who can "
        "compute accurately and, just as importantly, can say why the computation works."
    ),
    "philosophy": (
        "The central risk of Grade 2 is that a child learns the standard algorithm as a ritual — a sequence of "
        "marks with no meaning. Վարժարան teachers introduce every multi-digit procedure through place-value "
        "materials and expanded notation first, and require the student to explain a regrouping in terms of "
        "trading ten ones for one ten before the compact written form is permitted. Understanding is not a "
        "supplement to procedure here; it is the thing that makes procedure survive to Grade 4."
    ),
    "readiness": [
        ("Adds and subtracts within 20 without finger counting",
         "If absent, revisit Grade 1 Unit 3 before beginning; multi-digit work will otherwise collapse."),
        ("Explains that the 4 in 47 means four tens",
         "Place-value understanding, not just numeral reading, is the prerequisite for regrouping."),
        ("Solves a one-step word problem within 20 and writes an equation for it",
         "Indicates the child can move between situation and symbol."),
        ("Counts by 10s from any number",
         "Prerequisite for adding tens and for skip counting toward multiplication."),
    ],
    "outcomes": [
        "Understand place value to 1,000, including hundreds, tens, and ones, and count within 1,000.",
        "Fluently add and subtract within 100 using strategies based on place value and properties of operations.",
        "Add and subtract within 1,000 using concrete models and written strategies, and explain the reasoning.",
        "Know all sums of two one-digit numbers from memory.",
        "Solve one- and two-step word problems within 100 involving all four problem types.",
        "Measure and estimate length in inches, feet, centimeters, and meters, and choose an appropriate tool.",
        "Work with equal groups, arrays, and repeated addition as a foundation for multiplication.",
        "Tell time to the nearest five minutes and solve problems with dollar bills and coins.",
        "Draw a picture graph and a bar graph and answer comparison questions from them.",
    ],
    "units": [
        {"n": 1, "name_en": "Place Value to 1,000", "name_hy": "Կարգային արժեք մինչև 1000",
         "lessons": "7–8 lessons",
         "topics": ["Bundling ten tens into one hundred", "Three-digit numbers as hundreds, tens, and ones",
                    "Standard, expanded, and word form", "Counting within 1,000 by 1s, 5s, 10s, and 100s",
                    "Skip counting from any starting number", "Comparing three-digit numbers with >, <, =",
                    "10 more/less and 100 more/less, mentally"],
         "objectives": ["Explain 100 as a bundle of ten tens.",
                        "Write any number to 1,000 in standard, expanded, and word form.",
                        "Compare three-digit numbers by reasoning from the largest place downward.",
                        "Mentally add or subtract 10 or 100 to any three-digit number."],
         "mastery": ["Converts fluently among the three forms in 9 of 10 trials.",
                     "Compares three-digit numbers correctly in 9 of 10 trials with place-value justification.",
                     "Answers '100 less than 428' in under 4 seconds."],
         "misconceptions": [
             ("The child writes 'three hundred forty-two' as 30042.",
              "Concatenation error — the child is writing what they hear. Build the number with base-ten blocks and write expanded form as an intermediate step."),
             ("Zero as a placeholder is dropped: 405 written as 45.",
              "Explicitly practice numbers with internal zeros; use place-value charts where the empty column must be filled."),
         ],
         "note": "Everything in Grade 2 rests on this unit. Base-ten blocks — physical or on the shared whiteboard — should be visible in every lesson of the unit."},

        {"n": 2, "name_en": "Addition and Subtraction Within 100", "name_hy": "Գումարում և հանում 100-ի սահմաններում",
         "lessons": "9–10 lessons",
         "topics": ["Adding and subtracting tens", "Adding two-digit numbers without regrouping",
                    "Regrouping ones into a ten: the meaning before the notation", "The standard algorithm for addition",
                    "Regrouping a ten into ones for subtraction", "The standard algorithm for subtraction",
                    "Mental strategies: compensation, adding up, near-doubles", "Checking subtraction with addition",
                    "Adding four two-digit numbers"],
         "objectives": ["Add and subtract within 100 fluently, choosing between mental and written methods.",
                        "Explain a regrouping as a trade of ten ones for one ten, using blocks or drawings.",
                        "Use compensation (e.g., 48 + 27 as 50 + 25) as a mental strategy.",
                        "Verify a subtraction result by adding."],
         "mastery": ["Computes 20 two-digit sums and differences with 90% accuracy in 5 minutes.",
                     "Explains one regrouping step aloud in place-value language.",
                     "Uses at least one mental strategy correctly without prompting."],
         "misconceptions": [
             ("The child subtracts the smaller digit from the larger regardless of position (52 − 27 = 35).",
              "The most common error in Grade 2. Model with blocks: you cannot take 7 from 2, so you must unbundle a ten. Never let the child proceed on the written form until the block model is correct."),
             ("The regrouped 1 is written but never added.",
              "Slow down and name it: 'that one is one ten, and it belongs in the tens column.' Use color to mark it."),
         ],
         "note": "Fluency within 100 is the expected exit skill. Fluent means accurate, reasonably quick, and flexible — a student who only knows the algorithm is not yet fluent."},

        {"n": 3, "name_en": "Addition and Subtraction Within 1,000", "name_hy": "Գումարում և հանում 1000-ի սահմաններում",
         "lessons": "7–8 lessons",
         "topics": ["Adding three-digit numbers with base-ten models", "Regrouping in two places",
                    "Subtracting across a zero", "Written strategies and the standard algorithm extended",
                    "Estimating sums and differences by rounding to the nearest hundred",
                    "Judging whether an answer is reasonable"],
         "objectives": ["Add and subtract within 1,000 using models and written strategies, explaining each regrouping.",
                        "Subtract across a zero correctly (e.g., 400 − 137).",
                        "Estimate a sum before computing and use the estimate to check the result."],
         "mastery": ["Solves three-digit problems with regrouping in two places at 85% accuracy.",
                     "Solves 4 of 5 subtract-across-zero problems correctly.",
                     "Produces a reasonable estimate before computing in 4 of 5 tasks."],
         "misconceptions": [
             ("Subtracting across a zero produces errors like 400 − 137 = 373.",
              "Model unbundling twice with blocks: one hundred becomes ten tens, one ten becomes ten ones. Rushing this creates a gap that persists to Grade 5."),
             ("The child estimates *after* computing, to match the answer.",
              "Require the estimate to be written down and circled before any computation begins."),
         ],
         "note": "Estimation is not decoration. A student who estimates first catches their own place-value errors, which is the whole point."},

        {"n": 4, "name_en": "Measurement, Length, and the Number Line", "name_hy": "Չափում, երկարություն և թվային առանցք",
         "lessons": "7–8 lessons",
         "topics": ["Measuring with rulers, yardsticks, meter sticks, and tapes", "Inches and feet; centimeters and meters",
                    "Choosing an appropriate unit and tool", "Estimating lengths before measuring",
                    "Comparing lengths and finding the difference", "Adding and subtracting lengths within 100",
                    "Representing whole numbers as points on a number line", "Solving length problems on a number line"],
         "objectives": ["Measure the same object in two different units and explain why the numbers differ.",
                        "Estimate a length in a given unit before measuring, then check.",
                        "Use a number line diagram to represent and solve an addition or subtraction problem."],
         "mastery": ["Measures to the nearest whole unit accurately in 4 of 5 trials.",
                     "Explains why measuring in centimeters gives a larger number than inches.",
                     "Correctly places and uses jumps on a number line for a two-step problem."],
         "misconceptions": [
             ("Measurement begins at the end of the ruler rather than at the zero mark.",
              "Deliberately hand the child a broken ruler starting at 3; ask how to measure with it. This forces attention to the zero point."),
             ("A larger unit is assumed to give a larger number.",
              "Measure a desk in inches and in feet side by side. The inverse relationship must be experienced, not told."),
         ],
         "note": "The number line introduced here becomes the backbone of fractions in Grade 3 and of integers in Grade 6. Treat it as a major idea, not a diagram."},

        {"n": 5, "name_en": "Foundations of Multiplication", "name_hy": "Բազմապատկման հիմքեր",
         "lessons": "6–7 lessons",
         "topics": ["Equal groups and the language of 'groups of'", "Repeated addition",
                    "Building and describing rectangular arrays", "Rows and columns; finding the total two ways",
                    "Skip counting by 2s, 5s, and 10s as repeated addition", "Even and odd numbers via pairing",
                    "Writing an equation for an array as a sum of equal addends"],
         "objectives": ["Represent an equal-groups situation with objects, an array, and a repeated-addition equation.",
                        "Find the total in an array by counting rows and by counting columns, and explain why both work.",
                        "Determine whether a number is even or odd by pairing, and justify."],
         "mastery": ["Builds an array for a given equal-groups story in 4 of 5 trials.",
                     "Writes a correct repeated-addition equation for an array.",
                     "Classifies numbers to 20 as even or odd with justification."],
         "misconceptions": [
             ("The child treats a 3 × 4 array and a 4 × 3 array as unrelated.",
              "Physically rotate the array. Seeing the same object from two orientations is the concrete root of commutativity."),
             ("'Even' is defined as 'ends in 0, 2, 4, 6, 8' with no meaning attached.",
              "Define even as 'can be split into two equal groups with none left over' and let the digit pattern be a discovered consequence."),
         ],
         "note": "No multiplication symbol is required this year, but the array model introduced here is the same model used for multi-digit multiplication in Grade 4 and for area in Grade 3. Build it well."},

        {"n": 6, "name_en": "Time, Money, Data, and Shapes", "name_hy": "Ժամանակ, փող, տվյալներ և պատկերներ",
         "lessons": "7–8 lessons",
         "topics": ["Telling time to the nearest five minutes; a.m. and p.m.", "Elapsed time in whole and half hours",
                    "Counting mixed collections of coins and bills", "Solving money word problems with $ and ¢ symbols",
                    "Generating measurement data and making a line plot", "Picture graphs and bar graphs with single-unit scales",
                    "Answering put-together, take-apart, and compare questions from a graph",
                    "Recognizing and drawing shapes by number of angles and faces", "Partitioning rectangles into equal squares"],
         "objectives": ["Tell and write time to the nearest five minutes on analog and digital clocks.",
                        "Count a mixed collection of coins and bills and write the amount correctly.",
                        "Draw a bar graph from a data set and answer a comparison question about it.",
                        "Partition a rectangle into rows and columns of same-size squares and count them."],
         "mastery": ["Reads five-minute times correctly in 9 of 10 trials.",
                     "Counts a mixed coin collection under $2.00 accurately in 4 of 5 trials.",
                     "Constructs a correct bar graph with labeled axes from raw data."],
         "misconceptions": [
             ("Coins are counted by quantity rather than by value.",
              "Sort by value from largest to smallest before counting, and count on: 25, 35, 45, 50."),
             ("Bar graph bars are drawn without a consistent scale.",
              "Require axis labels and a stated scale on every graph, every time, from the first example."),
         ],
         "note": "Partitioning rectangles into same-size squares is quietly the beginning of area. Connect it aloud to the arrays of Unit 5."},
    ],
    "assessment": [
        ("Placement Assessment", "Before enrollment", "Grade 1 exit skills plus early Grade 2 content; produces the initial academic profile."),
        ("Unit Check", "End of each unit · 15 min", "That unit's mastery criteria; oral explanation is scored alongside accuracy."),
        ("Fluency Probe", "Every 3rd lesson · 3 min", "Sums within 20 from memory, then two-digit computation."),
        ("Mid-Year Assessment", "After Unit 3", "Cumulative Units 1–3, weighted toward place value and regrouping."),
        ("End-of-Course Assessment", "After Unit 6", "All course outcomes; determines Grade 3 placement and pacing."),
    ],
    "pacing": [
        ("Standard", "1 lesson/week, 45–50 min", "Full course in approximately 40–45 weeks."),
        ("Accelerated", "2 lessons/week", "Full course in approximately 22–25 weeks."),
        ("Intensive / Catch-Up", "2–3 lessons/week", "16–20 weeks; typically Units 1–3 first, then the remainder."),
        ("Summer Program", "3 lessons/week, 6 weeks", "Regrouping intensive (Units 2–3) or full-year preview."),
    ],
    "homework": (
        "Fifteen minutes per lesson, six to eight problems. Every assignment contains at least two problems from a "
        "prior unit — spaced retrieval is what keeps Grade 1 fluency from decaying while Grade 2 content is being "
        "learned. Word problems are always included, never postponed to the end of the year. Parents record the time "
        "spent and any problem that caused frustration; the teacher reviews this before the next lesson."
    ),
    "milestones": [
        "Reads, writes, and compares any number to 1,000 in three forms.",
        "Knows all sums of two one-digit numbers from memory.",
        "Adds and subtracts fluently within 100.",
        "Explains regrouping in place-value language, not as a rule.",
        "Adds and subtracts within 1,000, including across a zero.",
        "Measures and estimates length in both customary and metric units.",
        "Represents equal groups with arrays and repeated addition.",
        "Tells time to five minutes and counts mixed money.",
        "Completed Grade 2 Mathematics — ready for Grade 3.",
    ],
    "materials": [
        "Base-ten blocks (hundreds flats, tens rods, ones cubes) — physical set at home and digital on the shared board.",
        "Rulers in inches and centimeters; a measuring tape.",
        "US coins and bills (play money) for the money unit.",
        "Վարժարան Grade 2 problem bank — approximately 800 items tagged by unit, type, and difficulty.",
    ],
})

# ---------------------------------------------------------------- GRADE 3
COURSES.append({
    "code": "MTH-G3",
    "title_en": "Grade 3 Mathematics",
    "title_hy": "Մաթեմատիկա — 3-րդ դասարան",
    "band": BAND, "band_hy": BAND_HY,
    "grade_label": "Grade 3 · typical age 8–9",
    "hours": "72–84 instructional hours (approx. 66 lessons)",
    "prereq": "Grade 2 Mathematics or equivalent: fluency within 100, place value to 1,000, arrays and equal groups.",
    "next": "Grade 4 Mathematics (MTH-G4)",
    "description": (
        "Grade 3 is the pivot year of elementary mathematics. Two ideas of permanent consequence arrive at once: "
        "multiplication and division as operations in their own right, and fractions as numbers rather than as "
        "pieces of a picture. Students also meet area as a measurable quantity, extend arithmetic to larger "
        "numbers, and begin to solve genuinely two-step problems. A student who leaves Grade 3 with secure "
        "multiplication facts and a number-line understanding of fractions is set up for everything that follows."
    ),
    "philosophy": (
        "Two commitments define how Վարժարան teaches Grade 3. First, multiplication facts are built through "
        "structure — skip counting, arrays, the distributive property, and derived facts — and only then "
        "automatized; drilling before understanding produces brittle recall that fails under multi-digit load. "
        "Second, fractions are taught on the number line from the very first lesson, not only as shaded regions. "
        "The pizza model alone is the single largest cause of fraction failure in Grades 5–7, because it never "
        "shows the student that 3/4 is a number with a location."
    ),
    "readiness": [
        ("Adds and subtracts within 100 fluently",
         "Multi-digit work and two-step problems both depend on this; remediate before Unit 4 if weak."),
        ("Builds and interprets a rectangular array",
         "Direct prerequisite for multiplication; if absent, begin with Grade 2 Unit 5."),
        ("Skip counts by 2s, 5s, and 10s from any start",
         "Provides the first multiplication facts and the rhythm for the rest."),
        ("Partitions a shape into equal shares and names one share",
         "The conceptual entry point for fractions."),
    ],
    "outcomes": [
        "Interpret products and quotients of whole numbers in terms of equal groups, arrays, and area.",
        "Know all products of two one-digit numbers from memory by the end of the course.",
        "Apply the commutative, associative, and distributive properties as strategies for multiplication.",
        "Understand division as an unknown-factor problem and solve division within 100.",
        "Solve two-step word problems using all four operations and assess the reasonableness of answers.",
        "Understand a fraction 1/b as one part of a whole partitioned into b equal parts, and a/b as a copies of 1/b.",
        "Represent fractions on a number line and generate and explain equivalent fractions.",
        "Compare fractions with the same numerator or the same denominator and justify the comparison.",
        "Understand area as covering with unit squares, and relate area to multiplication and addition.",
        "Solve problems involving perimeter, elapsed time, mass, liquid volume, and scaled graphs.",
    ],
    "units": [
        {"n": 1, "name_en": "Meaning of Multiplication", "name_hy": "Բազմապատկման իմաստը",
         "lessons": "8–9 lessons",
         "topics": ["Interpreting 5 × 7 as five groups of seven", "Arrays, area models, and equal-groups pictures",
                    "The multiplication symbol and reading equations aloud", "The commutative property and why it halves the work",
                    "Facts for 2, 5, and 10 from skip counting", "Facts for 0 and 1 and why they behave as they do",
                    "The distributive property concretely: 7 × 6 as 5 × 6 plus 2 × 6",
                    "Deriving 3s, 4s, 6s, and 8s from known facts", "Multiplying by multiples of 10"],
         "objectives": ["Write a multiplication equation for an equal-groups or array situation and interpret each factor.",
                        "Use a known fact to derive an unknown one via the distributive property.",
                        "Explain why 4 × 7 = 7 × 4 using an array, in words.",
                        "Multiply a one-digit number by a multiple of 10 using place-value reasoning."],
         "mastery": ["Interprets both factors correctly in context in 9 of 10 trials.",
                     "Derives at least three unknown facts from known facts, explaining the decomposition.",
                     "Reaches 80% accuracy on facts for 0, 1, 2, 5, and 10 with under 4 seconds per item."],
         "misconceptions": [
             ("'Multiplication makes bigger' is adopted as a rule.",
              "True for whole numbers above 1, false everywhere else. Never state it. Preempt it by including × 1 and × 0 early and by noting aloud that this will change with fractions."),
             ("The child does not know which factor is the group count and which is the group size.",
              "Insist on a consistent convention in stories and then show that the product is the same either way — the *interpretation* differs even though the answer does not."),
         ],
         "note": "Introduce the area model here, not later. It is the same model that carries multi-digit multiplication in Grade 4, fraction multiplication in Grade 5, and binomial multiplication in Algebra I."},

        {"n": 2, "name_en": "Division and the Multiplication Facts", "name_hy": "Բաժանում և բազմապատկման աղյուսակ",
         "lessons": "8–9 lessons",
         "topics": ["Partitive division: sharing equally among a known number of groups",
                    "Quotitive division: measuring out groups of a known size", "The division symbol and notation",
                    "Division as an unknown-factor problem", "Fact families linking multiplication and division",
                    "Dividing by 1 and the impossibility of dividing by 0", "Systematic fluency work on all facts to 10 × 10",
                    "Solving one-step multiplication and division word problems"],
         "objectives": ["Distinguish sharing situations from measuring situations and model each correctly.",
                        "Rewrite a division problem as a missing-factor multiplication problem.",
                        "Know from memory all products of two one-digit numbers.",
                        "Explain why division by zero has no answer, using an equal-groups argument."],
         "mastery": ["Answers 60 mixed facts to 10 × 10 with 90% accuracy in 3 minutes.",
                     "Writes the complete fact family for a given triple in 5 of 5 trials.",
                     "Correctly models both division meanings for the same numerical problem."],
         "misconceptions": [
             ("Division is assumed to be commutative: 12 ÷ 3 treated as 3 ÷ 12.",
              "Contrast with subtraction, which the student already knows is not commutative. Model both with objects and let the child see one is impossible."),
             ("Fact fluency is pursued through timed drill alone and stalls around the 6s, 7s, and 8s.",
              "Switch to derived-fact strategies: 7 × 8 as 7 × 4 doubled, or 8 × 8 minus 8. Structure unlocks what drill cannot."),
         ],
         "note": "Automatic recall of the multiplication facts by the end of Grade 3 is the strongest single predictor of Grade 5–7 success. Fluency work continues in every lesson for the rest of the year, even after this unit closes."},

        {"n": 3, "name_en": "Fractions as Numbers", "name_hy": "Կոտորակները որպես թվեր",
         "lessons": "10–11 lessons",
         "topics": ["Partitioning a whole into b equal parts; the unit fraction 1/b",
                    "Building a/b as a copies of the unit fraction", "Fractions on the number line between 0 and 1",
                    "Fractions greater than 1 on the number line", "Whole numbers as fractions (3 = 3/1, 4/4 = 1)",
                    "Equivalent fractions through partitioning and on the number line",
                    "Recognizing simple equivalences: 1/2 = 2/4 = 3/6", "Comparing fractions with the same denominator",
                    "Comparing fractions with the same numerator", "Comparing to the benchmark 1/2",
                    "Why comparisons require the same whole"],
         "objectives": ["Locate any fraction with denominator 2, 3, 4, 6, or 8 on a number line and explain the placement.",
                        "Explain a/b as a copies of 1/b using a drawing and a number line.",
                        "Generate an equivalent fraction and justify it with a partitioned model.",
                        "Compare two fractions with the same numerator and explain why the larger denominator gives the smaller fraction."],
         "mastery": ["Places fractions correctly on a number line in 9 of 10 trials.",
                     "Justifies an equivalence with a model, not a rule, in 4 of 5 trials.",
                     "Compares same-numerator fractions correctly in 9 of 10 trials with reasoning."],
         "misconceptions": [
             ("A larger denominator is assumed to mean a larger fraction, because 8 > 4.",
              "The denominator names the size of the piece, not the count. Fold identical paper strips into 4 and into 8 and compare a single piece from each — physically."),
             ("Fractions are seen only as shaded parts of a shape, never as numbers.",
              "Every fraction lesson in this unit must include a number-line representation. This is non-negotiable at Վարժարան."),
             ("Comparisons are made across different wholes (1/2 of a large pizza vs. 3/4 of a small one).",
              "State explicitly and often: comparisons are only valid when the whole is the same. Use a deliberate counterexample."),
         ],
         "note": "This is the most important unit in the elementary curriculum. Grade 5–7 fraction failure is almost always traceable to a Grade 3 unit taught in two weeks with pizzas. Give it the time it needs."},

        {"n": 4, "name_en": "Area and Perimeter", "name_hy": "Մակերես և պարագիծ",
         "lessons": "6–7 lessons",
         "topics": ["Area as covering a region with unit squares", "Measuring area by counting unit squares",
                    "Relating area to multiplication of side lengths", "Area of rectilinear figures by decomposition",
                    "The distributive property seen as area: a × (b + c)", "Perimeter as distance around",
                    "Distinguishing area from perimeter", "Rectangles with equal area but different perimeter, and vice versa"],
         "objectives": ["Find the area of a rectangle by tiling and by multiplying, and show these agree.",
                        "Decompose a rectilinear figure into rectangles and add the areas.",
                        "Find an unknown side length given the perimeter and the other sides.",
                        "Construct two rectangles with the same area and different perimeters."],
         "mastery": ["Computes rectangle area correctly with units in 9 of 10 trials.",
                     "Decomposes an L-shaped figure and finds total area in 4 of 5 trials.",
                     "Explains the difference between area and perimeter in the student's own words."],
         "misconceptions": [
             ("Area and perimeter formulas are confused with each other.",
              "Do not lead with formulas. Have the student walk the perimeter with a finger and cover the area with squares. The physical distinction precedes the symbolic one."),
             ("Square units are reported as linear units.",
              "Require correct units on every answer from the first lesson; treat a missing 'square' as an incorrect answer."),
         ],
         "note": "Area is where multiplication becomes geometric. Explicitly show that the area model of Unit 1 and the area of Unit 4 are the same picture."},

        {"n": 5, "name_en": "Multi-Digit Arithmetic and Two-Step Problems", "name_hy": "Բազմանիշ թվաբանություն և երկքայլ խնդիրներ",
         "lessons": "7–8 lessons",
         "topics": ["Fluent addition and subtraction within 1,000", "Rounding to the nearest 10 and 100",
                    "Estimating to check reasonableness", "Multiplying one-digit numbers by multiples of 10",
                    "Two-step word problems with all four operations", "Representing unknowns with a letter or a box",
                    "Identifying arithmetic patterns in the addition and multiplication tables",
                    "Explaining a pattern using properties of operations"],
         "objectives": ["Solve two-step word problems and write an equation with a symbol for the unknown.",
                        "Round to the nearest 10 or 100 and use rounding to assess reasonableness.",
                        "Identify and explain a pattern in a multiplication table (e.g., why all products of 4 are even)."],
         "mastery": ["Solves two-step problems correctly in 8 of 10 trials with an equation shown.",
                     "Rounds correctly in 9 of 10 trials, including at the midpoint.",
                     "Explains one table pattern using a property of operations."],
         "misconceptions": [
             ("In a two-step problem, only the first step is completed.",
              "Require the student to restate the question in their own words before computing, and to check the answer against that restatement afterward."),
             ("Rounding is done by looking at the wrong digit.",
              "Use a number line and ask 'which ten is it closer to?' rather than teaching a digit rule."),
         ],
         "note": "Two-step problems are where reading comprehension and mathematics meet. Teachers should read the problem aloud with the student and model the underlining of the question."},

        {"n": 6, "name_en": "Measurement, Data, and Geometry", "name_hy": "Չափում, տվյալներ և երկրաչափություն",
         "lessons": "6–7 lessons",
         "topics": ["Telling time to the minute; elapsed-time problems on a number line",
                    "Measuring and estimating liquid volume and mass in metric units",
                    "Solving one-step problems involving mass and volume", "Scaled picture graphs and scaled bar graphs",
                    "Line plots with halves and fourths of an inch", "Classifying quadrilaterals by their attributes",
                    "Rhombuses, rectangles, and squares as related categories", "Partitioning shapes into equal areas and naming the share"],
         "objectives": ["Solve an elapsed-time problem using a number line.",
                        "Read a scaled bar graph where one square represents more than one unit.",
                        "Classify quadrilaterals by attributes and explain why a square is also a rectangle.",
                        "Measure lengths to the nearest quarter inch and display them on a line plot."],
         "mastery": ["Solves elapsed-time problems correctly in 8 of 10 trials.",
                     "Interprets a scaled graph correctly in 4 of 5 trials.",
                     "Correctly explains one shape-category inclusion relationship."],
         "misconceptions": [
             ("On a scaled graph each square is read as one unit.",
              "Require the student to state the scale aloud before reading any value."),
             ("A square is not recognized as a rectangle.",
              "Category inclusion is genuinely hard at this age. Use attribute checklists rather than appearance."),
         ],
         "note": "Line plots with fractional measurements deliberately reunite Units 3 and 6. Point this out to the student — connections should be named, not left to chance."},
    ],
    "assessment": [
        ("Placement Assessment", "Before enrollment", "Grade 2 exit skills and readiness for multiplication; produces the initial academic profile."),
        ("Unit Check", "End of each unit · 20 min", "Unit mastery criteria; includes at least one 'explain your reasoning' item."),
        ("Multiplication Fluency Probe", "Weekly from Unit 2 onward · 3 min", "All facts to 10 × 10; tracked as a running chart the student can see."),
        ("Fraction Diagnostic", "During and after Unit 3", "Number-line placement, equivalence, and comparison; the highest-stakes internal check of the year."),
        ("Mid-Year Assessment", "After Unit 3", "Cumulative Units 1–3; weighted toward multiplication meaning and fractions."),
        ("End-of-Course Assessment", "After Unit 6", "All course outcomes; determines Grade 4 placement and whether fraction remediation is needed."),
    ],
    "pacing": [
        ("Standard", "1 lesson/week, 50 min", "Full course in approximately 45–50 weeks."),
        ("Accelerated", "2 lessons/week", "Full course in approximately 24–28 weeks."),
        ("Intensive / Catch-Up", "2–3 lessons/week", "18–22 weeks; Units 1–3 prioritized."),
        ("Fractions Intensive", "2 lessons/week, 6 weeks", "Unit 3 only — offered as a standalone remediation for students in Grades 4–6 with fraction gaps."),
    ],
    "homework": (
        "Twenty minutes per lesson. Every assignment includes a short multiplication-fact component (2–3 minutes) "
        "that continues from Unit 2 through the end of the course, regardless of the current topic — this is what "
        "produces automaticity by June. The remainder is three to five problems on current content plus one "
        "review problem. Word problems appear in every assignment."
    ),
    "milestones": [
        "Interprets multiplication and division in terms of equal groups and arrays.",
        "Knows all multiplication facts to 10 × 10 from memory.",
        "Understands division as an unknown-factor problem.",
        "Places fractions on a number line and explains a/b as a copies of 1/b.",
        "Generates and justifies equivalent fractions.",
        "Compares fractions with the same numerator or denominator, with reasoning.",
        "Relates area to multiplication and distinguishes it from perimeter.",
        "Solves two-step word problems with all four operations.",
        "Completed Grade 3 Mathematics — ready for Grade 4.",
    ],
    "materials": [
        "Fraction strips and fraction number-line kits (physical set at home, digital on the shared board).",
        "Square tiles for area work; grid paper.",
        "Multiplication fact chart — used as a pattern-discovery tool, not as a crutch during fluency work.",
        "Վարժարան Grade 3 problem bank — approximately 1,000 items, with a dedicated fraction sub-bank of 250.",
    ],
})

# ---------------------------------------------------------------- GRADE 4
COURSES.append({
    "code": "MTH-G4",
    "title_en": "Grade 4 Mathematics",
    "title_hy": "Մաթեմատիկա — 4-րդ դասարան",
    "band": BAND, "band_hy": BAND_HY,
    "grade_label": "Grade 4 · typical age 9–10",
    "hours": "72–84 instructional hours (approx. 66 lessons)",
    "prereq": "Grade 3 Mathematics or equivalent: multiplication facts to 10 × 10, fractions on a number line, area.",
    "next": "Grade 5 Mathematics (MTH-G5)",
    "description": (
        "Grade 4 scales everything up. Place value extends to a million and, crucially, students learn that each "
        "place is ten times the one to its right — the insight that makes decimals possible. Multi-digit "
        "multiplication and division arrive, fraction arithmetic begins with addition and subtraction of like "
        "denominators and multiplication by a whole number, and decimals appear as a new notation for tenths and "
        "hundredths. Geometry becomes measured, with angles, and classification becomes precise."
    ),
    "philosophy": (
        "Grade 4 is where procedural load rises sharply, and where students who memorized rather than understood "
        "in Grade 3 begin to fail. Վարժարան teachers therefore diagnose before they instruct: the placement "
        "assessment weights multiplication fluency and fraction meaning heavily, and gaps found there are closed "
        "before new content is layered on. Multi-digit algorithms are always introduced through the area model "
        "and partial products first, so that the compact algorithm is a shortening of something understood rather "
        "than a rule to obey."
    ),
    "readiness": [
        ("Recalls multiplication facts to 10 × 10 in under 4 seconds each",
         "Non-negotiable. Multi-digit multiplication with weak facts becomes an exercise in error accumulation."),
        ("Places fractions on a number line and explains equivalence with a model",
         "If absent, run the Grade 3 Fractions Intensive concurrently with Units 1–2."),
        ("Adds and subtracts within 1,000 fluently, including across zeros",
         "Prerequisite for the standard algorithm at larger magnitudes."),
        ("Finds the area of a rectangle and explains why the formula works",
         "The area model is the vehicle for all multi-digit multiplication this year."),
    ],
    "outcomes": [
        "Recognize that a digit in one place represents ten times what it represents in the place to its right.",
        "Read, write, compare, and round multi-digit whole numbers to one million.",
        "Fluently add and subtract multi-digit whole numbers using the standard algorithm.",
        "Multiply a four-digit number by a one-digit number, and two two-digit numbers, using place-value strategies.",
        "Find whole-number quotients and remainders with up to four-digit dividends and one-digit divisors.",
        "Interpret a multiplication equation as a comparison and solve multiplicative comparison problems.",
        "Find factor pairs, identify prime and composite numbers, and generate and analyze patterns.",
        "Explain fraction equivalence with visual models and compare fractions with unlike denominators.",
        "Add and subtract fractions and mixed numbers with like denominators; multiply a fraction by a whole number.",
        "Understand decimal notation for tenths and hundredths, and compare decimals.",
        "Measure and draw angles, and solve addition and subtraction problems involving angle measure.",
        "Classify two-dimensional figures by properties of lines and angles, and identify lines of symmetry.",
    ],
    "units": [
        {"n": 1, "name_en": "Place Value to One Million", "name_hy": "Կարգային արժեք մինչև միլիոն",
         "lessons": "6–7 lessons",
         "topics": ["The ten-times relationship between adjacent places", "Reading and writing numbers to 1,000,000",
                    "Standard, word, and expanded form for large numbers", "Comparing multi-digit numbers",
                    "Rounding to any place", "Fluent multi-digit addition and subtraction",
                    "Estimating sums and differences of large numbers"],
         "objectives": ["Explain that the 7 in 7,000 is ten times the 7 in 700.",
                        "Round a six-digit number to any specified place.",
                        "Add and subtract multi-digit numbers fluently using the standard algorithm."],
         "mastery": ["States the ten-times relationship correctly for any pair of adjacent places.",
                     "Rounds correctly to a specified place in 9 of 10 trials.",
                     "Computes multi-digit sums and differences at 90% accuracy."],
         "misconceptions": [
             ("Rounding is applied by looking at all following digits rather than the single next digit.",
              "Use a number line and midpoint reasoning. The digit rule should be a summary of the reasoning, not a substitute for it."),
             ("Periods (thousands, millions) are not used when reading large numbers.",
              "Teach reading in three-digit chunks with the period name attached; practice aloud."),
         ],
         "note": "The ten-times relationship is stated here for the first time as a general principle. Say it explicitly — it is what makes decimals in Unit 6 an extension rather than a new topic."},

        {"n": 2, "name_en": "Multi-Digit Multiplication", "name_hy": "Բազմանիշ բազմապատկում",
         "lessons": "9–10 lessons",
         "topics": ["Multiplicative comparison: 'three times as many'", "Distinguishing additive from multiplicative comparison",
                    "Multiplying by multiples of 10, 100, and 1,000", "The area model for two-digit by one-digit",
                    "Partial products written vertically", "Four-digit by one-digit multiplication",
                    "Two-digit by two-digit via the area model", "The standard algorithm as compressed partial products",
                    "Estimating products to check reasonableness", "Multi-step word problems involving multiplication"],
         "objectives": ["Represent a two-digit by two-digit product with an area model and connect each region to a partial product.",
                        "Multiply four-digit by one-digit and two-digit by two-digit numbers accurately.",
                        "Distinguish 'five more than' from 'five times as many' in a word problem.",
                        "Estimate a product before computing and use it to check."],
         "mastery": ["Draws a correct area model for a two-digit by two-digit product in 4 of 5 trials.",
                     "Computes two-digit by two-digit products at 85% accuracy.",
                     "Correctly classifies comparison problems as additive or multiplicative in 8 of 10 trials."],
         "misconceptions": [
             ("In two-digit by two-digit multiplication only two of the four partial products are computed.",
              "The classic error. The area model makes the missing regions visible — return to it whenever this appears, rather than repeating the algorithm."),
             ("The placeholder zero in the second partial product is omitted.",
              "Do not teach 'add a zero'. Teach that the second row multiplies by 30, not 3, so the product is ten times larger."),
         ],
         "note": "Do not rush to the standard algorithm. Students who spend three lessons on the area model make dramatically fewer errors for the following two years."},

        {"n": 3, "name_en": "Division, Factors, and Patterns", "name_hy": "Բաժանում, բաժանարարներ և օրինաչափություններ",
         "lessons": "8–9 lessons",
         "topics": ["Division with remainders and interpreting the remainder in context",
                    "Dividing multiples of 10 and 100", "Partial quotients as a written strategy",
                    "Four-digit dividends with one-digit divisors", "Checking division with multiplication",
                    "Finding all factor pairs of a number to 100", "Multiples, primes, and composites",
                    "Divisibility by 2, 5, and 10", "Generating a number or shape pattern from a rule",
                    "Identifying features of a pattern not stated in the rule"],
         "objectives": ["Divide a four-digit number by a one-digit number using partial quotients or the standard algorithm.",
                        "Interpret a remainder correctly in context (drop it, round up, or report it as a fraction).",
                        "List all factor pairs of any number to 100 and classify it as prime or composite.",
                        "Generate a pattern from a rule and describe a property the rule did not state."],
         "mastery": ["Divides accurately with remainders at 85% accuracy.",
                     "Interprets remainders correctly in context in 4 of 5 word problems.",
                     "Lists all factor pairs of a given number correctly in 9 of 10 trials."],
         "misconceptions": [
             ("The remainder is always discarded regardless of the question asked.",
              "Use three word problems with identical numbers but different questions — how many buses, how many left over, what fraction remains — and let the contrast do the teaching."),
             ("Factors and multiples are confused with one another.",
              "Anchor with language: factors are inside the number, multiples are beyond it. Use a factor rainbow and a multiple number line side by side."),
         ],
         "note": "Partial quotients is the more transparent method and should be secure before the standard algorithm is offered. Many students are best served by keeping partial quotients as their primary method through Grade 5."},

        {"n": 4, "name_en": "Fraction Equivalence and Comparison", "name_hy": "Կոտորակների համարժեքություն և համեմատում",
         "lessons": "7–8 lessons",
         "topics": ["Why multiplying numerator and denominator by the same number preserves value",
                    "Generating equivalent fractions with models and with reasoning",
                    "Simplifying fractions to lowest terms", "Comparing fractions with unlike denominators using benchmarks",
                    "Comparing by creating common denominators", "Comparing by creating common numerators",
                    "Ordering a set of fractions", "Fractions and decimals on the same number line"],
         "objectives": ["Explain why 3/4 = 6/8 in terms of partitioning each part into two.",
                        "Compare two fractions with unlike denominators by at least two different methods.",
                        "Order a set of four fractions and justify the ordering."],
         "mastery": ["Generates equivalent fractions correctly in 9 of 10 trials.",
                     "Compares unlike-denominator fractions correctly in 9 of 10 trials with stated reasoning.",
                     "Explains the equivalence rule with a model rather than by citing it."],
         "misconceptions": [
             ("The child adds the same number to numerator and denominator to make an equivalent fraction.",
              "Show with a model that 1/2 and 2/3 are not equal. Equivalence comes from re-partitioning, which is multiplicative, not additive."),
             ("Fractions are compared by numerator alone or denominator alone.",
              "Require the student to state which method they are using and why it applies to this pair."),
         ],
         "note": "The equivalence rule must be justified, not announced. A student who can only recite 'multiply top and bottom' will apply it to addition next year."},

        {"n": 5, "name_en": "Fraction Operations", "name_hy": "Գործողություններ կոտորակների հետ",
         "lessons": "8–9 lessons",
         "topics": ["Decomposing a fraction into a sum of unit fractions", "Adding and subtracting fractions with like denominators",
                    "Mixed numbers and improper fractions; converting between them",
                    "Adding and subtracting mixed numbers with like denominators, including regrouping",
                    "Multiplying a fraction by a whole number as repeated addition",
                    "Word problems involving fraction addition, subtraction, and multiplication by a whole number",
                    "Estimating fraction sums using benchmarks"],
         "objectives": ["Decompose 7/8 into unit fractions in more than one way and record it as an equation.",
                        "Add and subtract mixed numbers with like denominators, regrouping when necessary.",
                        "Multiply a fraction by a whole number and interpret the product in context.",
                        "Estimate whether a fraction sum is closer to 0, 1/2, or 1 before computing."],
         "mastery": ["Adds and subtracts like-denominator fractions and mixed numbers at 90% accuracy.",
                     "Converts between mixed and improper forms in 9 of 10 trials.",
                     "Solves fraction word problems correctly in 8 of 10 trials."],
         "misconceptions": [
             ("Denominators are added along with numerators: 1/4 + 1/4 = 2/8.",
              "Return to the unit-fraction meaning: one fourth plus one fourth is two fourths, because the *size* of the piece did not change. The number line makes this unmistakable."),
             ("When subtracting mixed numbers, regrouping is done as if the fraction part were base ten.",
              "Regroup one whole into the correct number of fractional parts — 3 1/5 becomes 2 6/5, not 2 11/5. Model with fraction strips."),
         ],
         "note": "Only like denominators this year. Resist parental pressure to introduce unlike denominators early; Grade 5 does it properly, and premature exposure produces the add-the-denominators error."},

        {"n": 6, "name_en": "Decimals, Measurement, and Geometry", "name_hy": "Տասնորդական կոտորակներ, չափում և երկրաչափություն",
         "lessons": "8–9 lessons",
         "topics": ["Tenths and hundredths as fractions and as decimals", "Decimal notation on a number line",
                    "Equivalence: 0.3 = 0.30 = 3/10 = 30/100", "Comparing decimals to hundredths",
                    "Adding tenths and hundredths by converting to a common denominator",
                    "Converting within a measurement system (km to m, kg to g, hr to min)",
                    "Solving measurement word problems including money and time",
                    "Points, lines, rays, segments, and angles", "Measuring and drawing angles with a protractor",
                    "Additive angle measure; finding an unknown angle",
                    "Classifying triangles and quadrilaterals by angles and sides", "Lines of symmetry"],
         "objectives": ["Write a fraction with denominator 10 or 100 as a decimal and locate it on a number line.",
                        "Compare two decimals to hundredths and justify with a model.",
                        "Measure an angle to the nearest degree with a protractor.",
                        "Find an unknown angle in a decomposed figure by addition or subtraction.",
                        "Classify a triangle by both its sides and its angles."],
         "mastery": ["Converts between fraction and decimal forms for tenths and hundredths in 9 of 10 trials.",
                     "Measures angles within ±2 degrees in 4 of 5 trials.",
                     "Classifies triangles and quadrilaterals correctly in 8 of 10 trials."],
         "misconceptions": [
             ("0.25 is judged greater than 0.3 because 25 > 3.",
              "Whole-number thinking imported into decimals. Use a hundredths grid: 0.3 is 30 squares, 0.25 is 25. Also write 0.30 explicitly."),
             ("The wrong protractor scale is read, giving 130° instead of 50°.",
              "Estimate first — acute or obtuse? — then measure. The estimate catches the scale error every time."),
         ],
         "note": "Decimals are introduced here as a *notation* for fractions with denominators 10 and 100, not as a separate number system. Grade 5 builds the operations; this year builds the meaning."},
    ],
    "assessment": [
        ("Placement Assessment", "Before enrollment", "Weighted toward multiplication fluency and fraction meaning; identifies gaps that must be closed before Unit 2."),
        ("Unit Check", "End of each unit · 25 min", "Unit mastery criteria plus one extended reasoning item."),
        ("Fluency Probe", "Every 2nd lesson · 3 min", "Multiplication and division facts; continues all year."),
        ("Fraction Diagnostic", "Before Unit 4 and after Unit 5", "Equivalence, comparison, and like-denominator operations."),
        ("Mid-Year Assessment", "After Unit 3", "Cumulative Units 1–3; heavily weighted toward multi-digit multiplication and division."),
        ("End-of-Course Assessment", "After Unit 6", "All course outcomes; determines Grade 5 placement."),
    ],
    "pacing": [
        ("Standard", "1 lesson/week, 50–60 min", "Full course in approximately 45–50 weeks."),
        ("Accelerated", "2 lessons/week", "Full course in approximately 24–28 weeks."),
        ("Intensive / Catch-Up", "2–3 lessons/week", "18–22 weeks with a diagnostic-driven unit order."),
        ("Summer Program", "3 lessons/week, 6 weeks", "Multi-digit operations intensive (Units 2–3) or fraction intensive (Units 4–5)."),
    ],
    "homework": (
        "Twenty-five minutes per lesson: five to seven problems, of which at least two are word problems and one is "
        "cumulative review. Fact fluency practice continues in short daily doses. Students are asked to show a model "
        "or a written strategy for at least one problem per assignment — an answer alone earns no credit on those "
        "items, because the model is what the teacher needs in order to diagnose."
    ),
    "milestones": [
        "Understands that each place is ten times the place to its right.",
        "Reads, writes, compares, and rounds numbers to one million.",
        "Multiplies four-digit by one-digit and two-digit by two-digit numbers.",
        "Divides four-digit dividends by one-digit divisors and interprets remainders in context.",
        "Finds all factor pairs and identifies primes and composites.",
        "Explains and generates equivalent fractions with justification.",
        "Adds and subtracts fractions and mixed numbers with like denominators.",
        "Multiplies a fraction by a whole number.",
        "Reads, writes, and compares decimals to hundredths.",
        "Measures and draws angles and classifies 2-D figures by properties.",
        "Completed Grade 4 Mathematics — ready for Grade 5.",
    ],
    "materials": [
        "Base-ten blocks extended to thousands; place-value charts to millions.",
        "Fraction strips, fraction circles, and a hundredths grid.",
        "Protractor and straightedge (physical, at home).",
        "Grid paper for area models — used in nearly every lesson of Units 2 and 3.",
        "Վարժարան Grade 4 problem bank — approximately 1,100 items with model-required tagging.",
    ],
})

# ---------------------------------------------------------------- GRADE 5
COURSES.append({
    "code": "MTH-G5",
    "title_en": "Grade 5 Mathematics",
    "title_hy": "Մաթեմատիկա — 5-րդ դասարան",
    "band": BAND, "band_hy": BAND_HY,
    "grade_label": "Grade 5 · typical age 10–11",
    "hours": "72–84 instructional hours (approx. 66 lessons)",
    "prereq": "Grade 4 Mathematics or equivalent: multi-digit multiplication and division, fraction equivalence, decimals to hundredths.",
    "next": "Grade 6 Mathematics (MTH-G6)",
    "description": (
        "Grade 5 completes elementary arithmetic. Students finish the operations with fractions — including "
        "addition and subtraction with unlike denominators, multiplication of fractions by fractions, and "
        "division involving unit fractions — and extend the four operations to decimals through thousandths. "
        "Volume is introduced as a three-dimensional measure, the coordinate plane appears for the first time, "
        "and expressions with grouping symbols prepare the ground for algebra. By June the student should be "
        "able to compute confidently with any rational number they will meet in middle school."
    ),
    "philosophy": (
        "Grade 5 is the last year in which arithmetic can be repaired cheaply. Every gap left open here becomes a "
        "ratio problem in Grade 6, a proportional-reasoning problem in Grade 7, and an algebra problem in Grade 8. "
        "Վարժարան therefore treats Grade 5 as a consolidation year with an unusually rigorous diagnostic posture: "
        "the teacher's default assumption is that a wrong answer signals a conceptual gap upstream, not "
        "carelessness, and lesson time is spent finding it. Fraction multiplication and division are taught with "
        "models and language ('two thirds *of* six'), never as inverted rules to memorize."
    ),
    "readiness": [
        ("Multiplies two-digit by two-digit numbers accurately",
         "If weak, revisit Grade 4 Unit 2 area model — decimal multiplication will otherwise be unreachable."),
        ("Adds and subtracts fractions with like denominators and converts mixed numbers",
         "Direct prerequisite for Unit 2; a common gap in transferring students."),
        ("Compares decimals to hundredths and explains why",
         "Prerequisite for all decimal operations."),
        ("Divides four-digit by one-digit numbers with remainders",
         "Prerequisite for two-digit divisors and for decimal division."),
    ],
    "outcomes": [
        "Understand the place-value system through thousandths, including powers of ten and their exponents.",
        "Read, write, compare, and round decimals to thousandths.",
        "Fluently multiply multi-digit whole numbers using the standard algorithm.",
        "Divide up to four-digit dividends by two-digit divisors, explaining the reasoning.",
        "Add, subtract, multiply, and divide decimals to hundredths, and explain the reasoning used.",
        "Add and subtract fractions and mixed numbers with unlike denominators.",
        "Multiply a fraction by a fraction and interpret the product as scaling (resizing).",
        "Divide a unit fraction by a whole number and a whole number by a unit fraction.",
        "Interpret a fraction as division of the numerator by the denominator.",
        "Write and interpret numerical expressions using parentheses, brackets, and braces.",
        "Generate two numerical patterns from rules, form ordered pairs, and graph them.",
        "Understand volume as a three-dimensional measure and find volumes of right rectangular prisms.",
        "Graph points in the first quadrant and classify two-dimensional figures in a hierarchy.",
    ],
    "units": [
        {"n": 1, "name_en": "Place Value, Decimals, and Powers of Ten", "name_hy": "Կարգային արժեք, տասնորդականներ և տասի աստիճաններ",
         "lessons": "8–9 lessons",
         "topics": ["Decimals through thousandths in standard, word, and expanded form",
                    "Each place as ten times the place to its right and one tenth of the place to its left",
                    "Powers of ten and exponent notation", "Multiplying and dividing by powers of ten and the movement of the decimal point",
                    "Comparing and ordering decimals to thousandths", "Rounding decimals to any place",
                    "Fluent multi-digit whole-number multiplication", "Division with two-digit divisors using partial quotients",
                    "Estimating quotients"],
         "objectives": ["Write a decimal to thousandths in expanded form using fractions and using powers of ten.",
                        "Explain why multiplying by 10 shifts digits one place left, in place-value terms.",
                        "Divide a four-digit number by a two-digit divisor and justify the quotient.",
                        "Round any decimal to a specified place."],
         "mastery": ["Compares and orders decimals to thousandths at 90% accuracy.",
                     "Divides by two-digit divisors at 85% accuracy with reasoning shown.",
                     "Explains the effect of multiplying by a power of ten without saying 'move the decimal'."],
         "misconceptions": [
             ("'Multiplying by ten adds a zero' — applied to decimals, giving 4.5 × 10 = 4.50.",
              "This is why the rule must never be taught as 'add a zero'. The digits shift because each is now worth ten times as much. Use a place-value chart with sliding digits."),
             ("More digits after the decimal point is read as a larger number.",
              "Compare 0.7 and 0.65 on a number line and with a thousandths grid. Annexing zeros to equalize digit counts also helps."),
         ],
         "note": "Powers of ten are introduced here with exponent notation. This is the student's first exponent — treat it as an event, and connect it explicitly to the ten-times rule from Grade 4."},

        {"n": 2, "name_en": "Adding and Subtracting Fractions with Unlike Denominators", "name_hy": "Տարբեր հայտարարով կոտորակների գումարում և հանում",
         "lessons": "8–9 lessons",
         "topics": ["Why unlike denominators cannot be added directly", "Finding common denominators with models",
                    "The least common denominator and why any common denominator works",
                    "Adding and subtracting fractions with unlike denominators",
                    "Adding and subtracting mixed numbers with unlike denominators, including regrouping",
                    "Estimating fraction sums with benchmarks 0, 1/2, and 1", "Multi-step fraction word problems",
                    "Assessing reasonableness of a fraction answer"],
         "objectives": ["Explain with a model why 1/2 + 1/3 is not 2/5.",
                        "Add and subtract fractions and mixed numbers with unlike denominators accurately.",
                        "Estimate a fraction sum with benchmarks and use the estimate to catch errors.",
                        "Solve a two-step word problem involving fraction addition and subtraction."],
         "mastery": ["Adds and subtracts unlike-denominator fractions at 90% accuracy.",
                     "Handles mixed-number subtraction with regrouping in 4 of 5 trials.",
                     "Produces a benchmark estimate before computing in 4 of 5 tasks."],
         "misconceptions": [
             ("Numerators and denominators are added separately.",
              "The defining error of Grade 5 fractions. Return to the unit-fraction meaning and to fraction strips — fourths and thirds are different-sized pieces and cannot be counted together."),
             ("Only the least common denominator is believed to work.",
              "Show that 1/2 + 1/3 gives the same result with denominator 6, 12, or 24. Understanding this frees the student from a lookup step and reduces anxiety."),
         ],
         "note": "Benchmark estimation is the single most effective self-checking habit in fraction work. Require it on every problem for the first four lessons until it becomes automatic."},

        {"n": 3, "name_en": "Multiplying and Dividing Fractions", "name_hy": "Կոտորակների բազմապատկում և բաժանում",
         "lessons": "9–10 lessons",
         "topics": ["A fraction as division: 3/4 as 3 ÷ 4", "Multiplying a fraction by a whole number, revisited",
                    "Multiplying a fraction by a fraction with an area model", "The meaning of 'of' in fraction multiplication",
                    "Multiplication as scaling: when does the product shrink?", "Multiplying mixed numbers",
                    "Area of a rectangle with fractional side lengths", "Dividing a whole number by a unit fraction",
                    "Dividing a unit fraction by a whole number", "Real-world division problems with fractions"],
         "objectives": ["Interpret 3/4 as 3 ÷ 4 and connect it to a sharing situation.",
                        "Multiply two fractions using an area model and explain the result.",
                        "Predict without computing whether a product will be larger or smaller than a given factor.",
                        "Model and solve 4 ÷ 1/2 and 1/2 ÷ 4, and explain why the answers differ."],
         "mastery": ["Multiplies fractions and mixed numbers at 90% accuracy.",
                     "Predicts the scaling effect correctly in 8 of 10 trials before computing.",
                     "Models both unit-fraction division types correctly in 4 of 5 trials."],
         "misconceptions": [
             ("'Multiplication makes bigger; division makes smaller' persists from Grade 3.",
              "Directly confront it. Compute 6 × 1/2 and 6 ÷ 1/2 side by side and ask the student to explain the surprise. This is a genuine conceptual shift and deserves a full lesson."),
             ("Common denominators are found before multiplying fractions.",
              "Over-generalization from Unit 2. Use the area model to show why multiplication needs no common denominator — the two operations do genuinely different things."),
             ("4 ÷ 1/2 is answered as 2.",
              "Ask 'how many halves fit in 4?' and model with fraction strips. The measurement interpretation of division makes this immediate."),
         ],
         "note": "Never teach 'keep-change-flip' this year. Grade 6 formalizes fraction division; Grade 5's job is to build the meaning that makes the Grade 6 rule sensible rather than magical."},

        {"n": 4, "name_en": "Decimal Operations", "name_hy": "Գործողություններ տասնորդական կոտորակների հետ",
         "lessons": "8–9 lessons",
         "topics": ["Adding and subtracting decimals with place-value alignment", "Estimating decimal sums and differences",
                    "Multiplying a decimal by a whole number", "Multiplying two decimals and reasoning about the decimal point",
                    "Why the number of decimal places in a product is what it is", "Dividing a decimal by a whole number",
                    "Dividing by a decimal using equivalent expressions", "Relating decimal operations to fraction operations",
                    "Money and measurement problems with decimals"],
         "objectives": ["Add and subtract decimals with correct alignment and explain why alignment is required.",
                        "Multiply two decimals and justify the placement of the decimal point using fractions or estimation.",
                        "Divide a decimal by a whole number and by a decimal.",
                        "Solve multi-step problems involving money and measurement."],
         "mastery": ["Computes all four decimal operations at 90% accuracy.",
                     "Justifies decimal-point placement by estimation or by fraction equivalence, not by a counting rule.",
                     "Solves multi-step decimal word problems correctly in 8 of 10 trials."],
         "misconceptions": [
             ("Decimals are added right-aligned like whole numbers: 3.5 + 0.42 = 3.92 becomes 3.47.",
              "Align by place value, not by the right edge. Annex zeros so both numbers show the same places; require this in writing."),
             ("The decimal-point rule for products is memorized and then misapplied.",
              "Estimate first: 4.2 × 3.1 is about 12, so the answer cannot be 1.302. Estimation makes the rule self-correcting."),
         ],
         "note": "Every decimal operation should be connected back to its fraction equivalent at least once. 0.3 × 0.4 is 3/10 × 4/10 = 12/100 — this is where the placement rule comes from, and students who see it once rarely misplace the point again."},

        {"n": 5, "name_en": "Volume and Measurement", "name_hy": "Ծավալ և չափում",
         "lessons": "6–7 lessons",
         "topics": ["Volume as a count of unit cubes", "Measuring volume by packing and by counting layers",
                    "The formulas V = l × w × h and V = B × h, and why they agree",
                    "Volume of solid figures composed of two right rectangular prisms",
                    "Converting among units within a measurement system", "Multi-step measurement conversion problems",
                    "Line plots with fractional data and problems drawn from them"],
         "objectives": ["Find the volume of a right rectangular prism by packing, by layering, and by formula, and show the three agree.",
                        "Decompose a composite solid into prisms and find the total volume.",
                        "Convert between units within a system in a multi-step problem."],
         "mastery": ["Computes volume correctly with cubic units in 9 of 10 trials.",
                     "Finds the volume of a composite figure in 4 of 5 trials.",
                     "Performs multi-step conversions correctly in 8 of 10 trials."],
         "misconceptions": [
             ("Volume is computed by adding the three dimensions.",
              "Return to packing with unit cubes. The layer model — area of the base times the number of layers — makes multiplication necessary rather than arbitrary."),
             ("Cubic units are omitted or written as square units.",
              "Require units on every answer; treat wrong units as a wrong answer."),
         ],
         "note": "Introduce V = B × h alongside V = l × w × h. The B × h form generalizes to cylinders and prisms in middle school; the l × w × h form does not."},

        {"n": 6, "name_en": "Expressions, Patterns, and the Coordinate Plane", "name_hy": "Արտահայտություններ, օրինաչափություններ և կոորդինատային հարթություն",
         "lessons": "7–8 lessons",
         "topics": ["Writing and evaluating numerical expressions with parentheses, brackets, and braces",
                    "Order of operations with grouping symbols", "Interpreting an expression without evaluating it",
                    "Generating two numerical patterns from two rules", "Forming ordered pairs from corresponding terms",
                    "The coordinate plane: axes, origin, and ordered pairs in the first quadrant",
                    "Graphing points and interpreting coordinate values in context",
                    "Graphing pattern relationships and describing what the graph shows",
                    "A hierarchy of two-dimensional figures based on properties"],
         "objectives": ["Write an expression for a described calculation without evaluating it (e.g., 'add 8 and 7, then multiply by 2').",
                        "Evaluate a nested expression using correct order of operations.",
                        "Generate two patterns, form ordered pairs, and graph them on the coordinate plane.",
                        "Explain why every square is a rectangle but not every rectangle is a square."],
         "mastery": ["Evaluates nested expressions correctly in 9 of 10 trials.",
                     "Graphs ordered pairs accurately in 9 of 10 trials.",
                     "Correctly places at least four quadrilateral types in a property hierarchy."],
         "misconceptions": [
             ("Coordinates are reversed: (3, 5) plotted as (5, 3).",
              "Use a consistent verbal routine — 'across the hall, then up the stairs' — and require the student to say it aloud until it is automatic."),
             ("Order of operations is applied strictly left to right.",
              "Grouping symbols and multiplication precedence must be practiced deliberately with contrasting pairs such as 2 + 3 × 4 and (2 + 3) × 4."),
         ],
         "note": "This unit is a bridge to Grade 6 and to algebra. Writing an expression *without* evaluating it is genuinely new thinking for a fifth-grader and deserves explicit attention — it is the first step toward treating a symbol string as an object."},
    ],
    "assessment": [
        ("Placement Assessment", "Before enrollment", "Weighted toward Grade 4 fraction and multi-digit operations; identifies gaps to close before Unit 2."),
        ("Unit Check", "End of each unit · 30 min", "Unit mastery criteria plus two extended reasoning items."),
        ("Fluency Probe", "Every 2nd lesson · 3 min", "Multiplication facts and multi-digit computation; continues all year."),
        ("Fraction Operations Diagnostic", "After Units 2 and 3", "The highest-stakes internal check of Grade 5; failure triggers targeted remediation before Unit 4."),
        ("Mid-Year Assessment", "After Unit 3", "Cumulative Units 1–3."),
        ("End-of-Course Assessment", "After Unit 6", "All course outcomes; determines Grade 6 placement and whether the student is ready for an accelerated middle school track."),
    ],
    "pacing": [
        ("Standard", "1 lesson/week, 60 min", "Full course in approximately 45–50 weeks."),
        ("Accelerated", "2 lessons/week", "Full course in approximately 24–28 weeks; recommended for students targeting Algebra I in Grade 7 or 8."),
        ("Intensive / Catch-Up", "2–3 lessons/week", "18–22 weeks with diagnostic-driven ordering."),
        ("Summer Program", "3 lessons/week, 6 weeks", "Fraction and decimal operations intensive (Units 2–4) — the most requested summer program at this level."),
    ],
    "homework": (
        "Thirty minutes per lesson: six to eight problems including at least two word problems and two cumulative "
        "review items. Beginning in Unit 2, every assignment requires the student to estimate before computing on at "
        "least one problem and to write the estimate down. Students who consistently finish in under fifteen minutes "
        "with full accuracy are flagged for the accelerated track."
    ),
    "milestones": [
        "Understands place value through thousandths and powers of ten.",
        "Multiplies multi-digit whole numbers fluently and divides by two-digit divisors.",
        "Adds and subtracts fractions and mixed numbers with unlike denominators.",
        "Multiplies fractions by fractions and interprets multiplication as scaling.",
        "Divides with unit fractions and explains why the answers behave as they do.",
        "Performs all four operations with decimals to hundredths.",
        "Understands volume and finds volumes of prisms and composite solids.",
        "Writes and evaluates expressions with grouping symbols.",
        "Graphs points and pattern relationships on the coordinate plane.",
        "Completed Grade 5 Mathematics — elementary arithmetic complete; ready for Grade 6.",
    ],
    "materials": [
        "Fraction strips, fraction circles, and area-model grids for fraction multiplication.",
        "Thousandths grids and place-value charts extending both directions from the decimal point.",
        "Unit cubes for volume (physical set at home strongly recommended).",
        "Coordinate grid paper.",
        "Վարժարան Grade 5 problem bank — approximately 1,200 items, with a 300-item fraction and decimal operations sub-bank.",
    ],
})
