# -*- coding: utf-8 -*-
"""Varzharan — Middle School Mathematics syllabi, Grades 6-8 and Pre-Algebra."""

BAND = "Middle School Mathematics"
BAND_HY = "Միջին դպրոցի մաթեմատիկա"

COURSES = []

# ---------------------------------------------------------------- GRADE 6
COURSES.append({
    "code": "MTH-G6",
    "title_en": "Grade 6 Mathematics",
    "title_hy": "Մաթեմատիկա — 6-րդ դասարան",
    "band": BAND, "band_hy": BAND_HY,
    "grade_label": "Grade 6 · typical age 11–12",
    "hours": "84–96 instructional hours (approx. 72 lessons)",
    "prereq": "Grade 5 Mathematics or equivalent: fraction and decimal operations, coordinate plane, volume.",
    "next": "Grade 7 Mathematics (MTH-G7)",
    "description": (
        "Grade 6 is where arithmetic becomes mathematics. Three genuinely new ideas arrive: ratio and rate as a "
        "way of comparing quantities multiplicatively, negative numbers as an extension of the number line in "
        "both directions, and the variable as a symbol that can stand for any number. Students complete division "
        "of fractions, become fluent with all decimal operations, meet statistical variability for the first "
        "time, and begin to write and solve one-step equations. The habits formed this year determine whether "
        "algebra will feel like a natural continuation or like a foreign language."
    ),
    "philosophy": (
        "Վարժարան treats Grade 6 as the beginning of the algebra pathway, not the end of elementary school. "
        "Teachers are asked to insist on precise language — a ratio is not a fraction, an expression is not an "
        "equation, a variable is not an abbreviation — because imprecision that is tolerable in Grade 6 becomes "
        "disabling in Algebra I. Ratio reasoning is developed with tables, tape diagrams, and double number "
        "lines before any cross-multiplication is permitted; students who reach for cross-multiplication early "
        "consistently fail the non-routine proportional problems of Grade 7."
    ),
    "readiness": [
        ("Performs all four operations with fractions and decimals accurately",
         "The computational floor for the entire course; weakness here shows up as ratio errors, not arithmetic errors."),
        ("Explains why dividing by 1/2 gives a larger result",
         "Signals whether fraction division was understood or memorized; predicts success in Unit 1."),
        ("Graphs points in the first quadrant of the coordinate plane",
         "Prerequisite for Unit 3 and for all later graphing."),
        ("Evaluates an expression with parentheses using order of operations",
         "Prerequisite for Unit 4; a very common gap in transferring students."),
    ],
    "outcomes": [
        "Understand ratio concepts and use ratio reasoning to solve real-world problems.",
        "Find unit rates and use them to compare, convert, and solve rate problems.",
        "Solve percent problems as rate-per-hundred, finding the part, the whole, or the percent.",
        "Interpret and compute quotients of fractions and explain the meaning of the result.",
        "Fluently divide multi-digit numbers and perform all four operations with multi-digit decimals.",
        "Find greatest common factors and least common multiples and apply the distributive property.",
        "Understand positive and negative numbers, absolute value, and ordering on the number line.",
        "Graph points in all four quadrants and solve problems using coordinates and absolute value.",
        "Write, read, and evaluate algebraic expressions and identify equivalent expressions.",
        "Solve one-variable one-step equations and inequalities and represent solutions on a number line.",
        "Analyze the relationship between dependent and independent variables using tables, graphs, and equations.",
        "Find areas of triangles and quadrilaterals, volumes of prisms with fractional edges, and surface areas using nets.",
        "Recognize a statistical question, summarize a distribution by center and spread, and interpret displays.",
    ],
    "units": [
        {"n": 1, "name_en": "Ratios and Rates", "name_hy": "Հարաբերություններ և արագություններ",
         "lessons": "10–11 lessons",
         "topics": ["The language of ratios: a:b, a to b, a/b, and when each is appropriate",
                    "Part-to-part and part-to-whole ratios", "Equivalent ratios and ratio tables",
                    "Tape diagrams and double number lines", "Unit rates and the meaning of 'per'",
                    "Comparing rates to make a decision (better buy problems)",
                    "Constant speed and distance-rate-time problems", "Converting measurement units by rate reasoning",
                    "Plotting equivalent ratios on the coordinate plane", "Percent as a rate per hundred",
                    "Finding the part, the whole, and the percent"],
         "objectives": ["Describe a ratio relationship in words and distinguish part-to-part from part-to-whole.",
                        "Generate equivalent ratios with a table and use the table to answer a question.",
                        "Compute a unit rate and use it to compare two options.",
                        "Solve a percent problem by treating percent as a rate per hundred, without a memorized formula.",
                        "Convert between measurement units by multiplying by a rate equal to one."],
         "mastery": ["Solves ratio problems with a table or diagram in 8 of 10 trials.",
                     "Computes and interprets a unit rate correctly in 9 of 10 trials.",
                     "Solves all three percent question types (find part, whole, percent) at 85% accuracy."],
         "misconceptions": [
             ("Ratios are treated additively: if 2:3 then 4:5.",
              "The defining error of Grade 6. Build a ratio table and a tape diagram together; the diagram makes the additive answer visibly wrong."),
             ("Percent is treated as a whole number rather than a rate, so 25% of 60 is answered as 25.",
              "Return to 'per hundred'. Use a 10 × 10 grid until the student can shade any percent and read the corresponding amount."),
             ("Cross-multiplication is used before the ratio relationship is understood.",
              "Withhold cross-multiplication entirely in this unit. It is a shortcut that hides the structure, and students who acquire it early cannot solve unfamiliar problems in Grade 7."),
         ],
         "note": "Ratio reasoning is the conceptual centre of middle school mathematics and the strongest predictor of Algebra I performance. Give this unit more time than the calendar suggests, and use visual models in every single lesson."},

        {"n": 2, "name_en": "The Number System: Fractions, Decimals, Factors", "name_hy": "Թվային համակարգ. կոտորակներ, տասնորդականներ, բաժանարարներ",
         "lessons": "9–10 lessons",
         "topics": ["Dividing a fraction by a fraction with visual models", "The invert-and-multiply rule and why it works",
                    "Word problems requiring fraction division", "Fluent multi-digit long division",
                    "All four operations with multi-digit decimals", "Greatest common factor of two numbers to 100",
                    "Least common multiple of two numbers to 12", "Factoring out a common factor with the distributive property",
                    "Prime factorization"],
         "objectives": ["Divide a fraction by a fraction using a model and explain the result in context.",
                        "Justify the invert-and-multiply rule rather than merely applying it.",
                        "Compute the GCF and LCM of a pair of numbers and choose which is needed in a given problem.",
                        "Rewrite a sum such as 36 + 8 as 4(9 + 2) using the distributive property."],
         "mastery": ["Divides fractions accurately and interprets the quotient in context in 8 of 10 trials.",
                     "Performs all four decimal operations at 90% accuracy.",
                     "Selects GCF vs. LCM correctly in 8 of 10 word problems."],
         "misconceptions": [
             ("Invert-and-multiply is applied to the wrong fraction, or to multiplication problems.",
              "Derive the rule once with a model: 3/4 ÷ 1/8 asks how many eighths fit in three fourths. A student who has seen the derivation applies it correctly."),
             ("GCF and LCM are confused in word problems.",
              "Ask a diagnostic question: is the answer smaller than the numbers (splitting into groups → GCF) or larger (events lining up → LCM)?"),
         ],
         "note": "The distributive-property factoring in this unit is quietly pre-algebra. Write 4(9 + 2) and then 4(x + 2) side by side in the final lesson to make the connection visible."},

        {"n": 3, "name_en": "Rational Numbers and the Coordinate Plane", "name_hy": "Ռացիոնալ թվեր և կոորդինատային հարթություն",
         "lessons": "8–9 lessons",
         "topics": ["Negative numbers in real contexts: temperature, elevation, debt",
                    "The number line extended in both directions", "Opposites and the meaning of −(−a)",
                    "Ordering rational numbers and interpreting the order in context",
                    "Absolute value as distance from zero", "Absolute value vs. order: −7 < −3 but |−7| > |−3|",
                    "All four quadrants of the coordinate plane", "Reflections across the axes and sign changes",
                    "Distance between points sharing a coordinate", "Polygons on the coordinate plane"],
         "objectives": ["Place any rational number on the number line and justify its position.",
                        "Interpret an inequality statement about negative numbers in a real context.",
                        "Explain absolute value as distance and distinguish it from ordering.",
                        "Find the distance between two points that share an x- or y-coordinate."],
         "mastery": ["Orders rational numbers including negatives correctly in 9 of 10 trials.",
                     "Distinguishes magnitude from order in 8 of 10 trials with justification.",
                     "Graphs and reflects points across both axes accurately in 9 of 10 trials."],
         "misconceptions": [
             ("−7 is judged greater than −3 because 7 > 3.",
              "The number line, always. Anchor with temperature: −7° is colder, therefore less. Insist on the context whenever the abstract ordering is unstable."),
             ("Absolute value is described as 'making a number positive'.",
              "This survives until it fails on |x| = 5 in Algebra. Define it as distance from zero from the first lesson and never use the shortcut phrase."),
         ],
         "note": "Negative numbers are the first idea in the curriculum with no direct physical model for the operations. Grade 6 builds only meaning and ordering; Grade 7 builds the operations. Do not rush ahead."},

        {"n": 4, "name_en": "Expressions and Equations", "name_hy": "Արտահայտություններ և հավասարումներ",
         "lessons": "10–11 lessons",
         "topics": ["Exponents and evaluating numerical expressions with exponents",
                    "Translating verbal phrases into algebraic expressions", "Vocabulary: term, coefficient, factor, constant, sum, product",
                    "Evaluating expressions at given values", "Applying properties to generate equivalent expressions",
                    "Combining like terms; expanding and factoring", "Identifying equivalent expressions by reasoning",
                    "The meaning of a solution to an equation", "Solving one-step equations by inverse operations",
                    "Writing an equation to represent a situation", "Inequalities of the form x > c and x < c",
                    "Representing inequality solutions on a number line"],
         "objectives": ["Translate a verbal description into an algebraic expression and back.",
                        "Determine whether two expressions are equivalent and justify with a property.",
                        "Solve a one-step equation and check the solution by substitution.",
                        "Write and graph an inequality representing a real constraint, and explain that it has infinitely many solutions."],
         "mastery": ["Translates between words and symbols correctly in 9 of 10 trials.",
                     "Solves one-step equations at 95% accuracy with checking shown.",
                     "Explains why an inequality has infinitely many solutions."],
         "misconceptions": [
             ("A variable is read as a label rather than a number (3s means '3 students').",
              "The 'student-professor' error, and it persists into calculus if untreated. Insist that s is *the number of* students. Substitute values immediately to make the variable behave like a number."),
             ("3x is read as 'three then x' rather than as multiplication.",
              "Evaluate 3x at several values in the first lesson. Ambiguity here corrupts everything downstream."),
             ("The equals sign is still read as 'compute the answer'.",
              "Use balance-scale imagery. Present equations with operations on both sides even before they are solvable, and ask whether they are true."),
         ],
         "note": "Precision of language is the whole point of this unit. Require the student to say 'the coefficient is 3' rather than 'the number in front', every time. Vocabulary is not decoration in algebra; it is how thinking is organized."},

        {"n": 5, "name_en": "Dependent Relationships, Area, and Volume", "name_hy": "Կախյալ մեծություններ, մակերես և ծավալ",
         "lessons": "9–10 lessons",
         "topics": ["Independent and dependent variables", "Representing a relationship with a table, a graph, and an equation",
                    "Moving between the three representations", "Area of triangles by decomposition and by formula",
                    "Area of parallelograms, trapezoids, and rhombi", "Area of composite and irregular polygons",
                    "Polygon area on the coordinate plane", "Volume of right rectangular prisms with fractional edge lengths",
                    "Nets of three-dimensional figures", "Surface area from a net"],
         "objectives": ["Identify the independent and dependent variable in a situation and write an equation relating them.",
                        "Produce a graph from a table and a table from an equation for the same relationship.",
                        "Derive the triangle area formula by relating it to a parallelogram.",
                        "Compute the surface area of a prism or pyramid from its net."],
         "mastery": ["Moves correctly among table, graph, and equation in 8 of 10 tasks.",
                     "Computes areas of triangles and quadrilaterals at 90% accuracy.",
                     "Computes surface area from a net correctly in 4 of 5 trials."],
         "misconceptions": [
             ("The slant side of a triangle is used as the height.",
              "The height must be perpendicular to the chosen base. Draw the altitude explicitly on every diagram, including obtuse triangles where it falls outside."),
             ("Surface area and volume are confused.",
              "Unfold the net physically. Surface area is what you paint; volume is what you fill. Require square units and cubic units respectively."),
         ],
         "note": "The three-representations idea introduced here is the organizing structure of all of Algebra I. Name it explicitly and return to it whenever a new relationship appears."},

        {"n": 6, "name_en": "Statistics and Distributions", "name_hy": "Վիճակագրություն և բաշխումներ",
         "lessons": "8–9 lessons",
         "topics": ["What makes a question statistical", "Variability as the reason statistics exists",
                    "Dot plots, histograms, and choosing bin width", "Describing a distribution: shape, center, spread",
                    "Mean as a fair share and as a balance point", "Median and when it is preferable to the mean",
                    "The effect of an outlier on mean and median", "Mean absolute deviation",
                    "Interquartile range and the five-number summary", "Box plots and comparing two distributions",
                    "Reporting a measure of center with the context and units"],
         "objectives": ["Distinguish a statistical question from a non-statistical one and explain why.",
                        "Construct a dot plot, histogram, and box plot from the same data set and say what each reveals.",
                        "Choose and justify an appropriate measure of center for a given distribution.",
                        "Describe how an outlier affects the mean but not the median, with a computed example."],
         "mastery": ["Identifies statistical questions correctly in 9 of 10 trials.",
                     "Constructs all three display types accurately from raw data.",
                     "Justifies a choice of center with reference to the shape of the distribution."],
         "misconceptions": [
             ("The mean is used automatically regardless of skew or outliers.",
              "Use a salary data set with one extreme value. Compute both measures and ask which better describes a typical person."),
             ("A histogram is treated as a bar graph.",
              "Bars touch because the horizontal axis is continuous. Have the student change the bin width and observe how the shape changes — bar graphs cannot do this."),
         ],
         "note": "Statistics is often taught last and rushed. It should not be: this unit introduces variability, which is the entire conceptual basis of AP Statistics and of quantitative reasoning generally."},
    ],
    "assessment": [
        ("Placement Assessment", "Before enrollment", "Grade 5 fraction and decimal operations plus early ratio reasoning; produces the initial academic profile."),
        ("Unit Check", "End of each unit · 35 min", "Unit mastery criteria plus two extended reasoning items requiring written justification."),
        ("Fluency Probe", "Every 3rd lesson · 5 min", "Fraction and decimal computation; maintained all year to prevent decay."),
        ("Ratio Reasoning Diagnostic", "During and after Unit 1", "Non-routine ratio problems that cannot be solved by cross-multiplication; the key predictor of Grade 7 readiness."),
        ("Mid-Year Assessment", "After Unit 3", "Cumulative Units 1–3."),
        ("End-of-Course Assessment", "After Unit 6", "All course outcomes; determines Grade 7 placement and eligibility for the accelerated algebra pathway."),
    ],
    "pacing": [
        ("Standard", "1 lesson/week, 60 min", "Full course in approximately 50–55 weeks."),
        ("Accelerated", "2 lessons/week", "Full course in approximately 28–32 weeks; recommended for students targeting Algebra I in Grade 8."),
        ("Compacted 6/7", "2 lessons/week", "Grade 6 and Grade 7 compressed across two years for students targeting Algebra I in Grade 7."),
        ("Intensive / Catch-Up", "2–3 lessons/week", "22–26 weeks with diagnostic-driven ordering."),
        ("Summer Program", "3 lessons/week, 6 weeks", "Ratios and rates intensive (Unit 1) — the highest-demand summer course in the middle school band."),
    ],
    "homework": (
        "Thirty to forty minutes per lesson: six to nine problems including two word problems, one cumulative review "
        "item, and one problem requiring a written explanation rather than a numerical answer. From Unit 4 onward "
        "every assignment includes at least one problem where the student must translate between words and symbols "
        "in both directions. Students are expected to attempt every problem and to mark — rather than skip — the "
        "ones they could not finish; an honest blank is more useful to the teacher than a guessed answer."
    ),
    "milestones": [
        "Uses ratio tables, tape diagrams, and double number lines to solve ratio problems.",
        "Computes and interprets unit rates and solves all three percent problem types.",
        "Divides fractions by fractions and explains why the rule works.",
        "Understands negative numbers, absolute value, and ordering on the number line.",
        "Graphs and reasons in all four quadrants of the coordinate plane.",
        "Writes, reads, and evaluates algebraic expressions with correct vocabulary.",
        "Solves one-step equations and inequalities and checks solutions.",
        "Moves fluently among tables, graphs, and equations for a relationship.",
        "Finds areas of polygons and surface areas from nets.",
        "Summarizes a distribution by center and spread and justifies the choice.",
        "Completed Grade 6 Mathematics — ready for Grade 7.",
    ],
    "materials": [
        "Digital ratio tables, tape diagrams, and double number lines on the shared whiteboard.",
        "Two-color counters and an extended number line for the rational-numbers unit.",
        "Nets of prisms and pyramids, printable for physical folding.",
        "Graphing tool for statistical displays (dot plot, histogram, box plot).",
        "Վարժարան Grade 6 problem bank — approximately 1,300 items, including a 200-item non-routine ratio sub-bank.",
    ],
})

# ---------------------------------------------------------------- GRADE 7
COURSES.append({
    "code": "MTH-G7",
    "title_en": "Grade 7 Mathematics",
    "title_hy": "Մաթեմատիկա — 7-րդ դասարան",
    "band": BAND, "band_hy": BAND_HY,
    "grade_label": "Grade 7 · typical age 12–13",
    "hours": "84–96 instructional hours (approx. 72 lessons)",
    "prereq": "Grade 6 Mathematics or equivalent: ratio reasoning, rational number ordering, one-step equations.",
    "next": "Grade 8 Mathematics (MTH-G8) or Algebra I (MTH-A1) on the accelerated pathway",
    "description": (
        "Grade 7 completes the number system and completes proportional reasoning. Students learn to add, "
        "subtract, multiply, and divide with all rational numbers including negatives; they recognize "
        "proportional relationships, identify the constant of proportionality, and interpret it as the slope of "
        "a line through the origin. Multi-step equations and inequalities appear, along with the geometry of "
        "circles, angle relationships, and scale drawings, and probability is introduced as a measurable "
        "quantity. This is the last full year before formal algebra."
    ),
    "philosophy": (
        "The central Վարժարան commitment in Grade 7 is that proportionality is a *relationship*, not a procedure. "
        "A student who recognizes proportionality in a table, a graph, an equation, and a verbal description — "
        "and who can also recognize when a situation is *not* proportional — has acquired the most transferable "
        "idea in secondary mathematics. Teachers are asked to include non-proportional situations deliberately "
        "and often, because a student who has only ever seen proportional examples has learned nothing except to "
        "multiply. Operations with negatives are developed with models and with the structure of the number "
        "system, not with sign rules recited in isolation."
    ),
    "readiness": [
        ("Solves a ratio problem with a table or diagram rather than by cross-multiplication",
         "Predicts success in Unit 2; students who can only cross-multiply must be retaught before proportionality."),
        ("Orders negative numbers correctly and explains absolute value as distance",
         "Prerequisite for Unit 1; a very common gap."),
        ("Solves one-step equations and checks the solution",
         "Prerequisite for multi-step equations in Unit 3."),
        ("Computes with fractions and decimals accurately",
         "Grade 7 combines negatives with fractions immediately; weak computation compounds."),
    ],
    "outcomes": [
        "Add, subtract, multiply, and divide rational numbers fluently, including negatives and fractions.",
        "Apply properties of operations to compute with rational numbers and to justify each step.",
        "Convert a rational number to a decimal and recognize that the decimal terminates or repeats.",
        "Compute unit rates associated with ratios of fractions, including rates in different units.",
        "Decide whether two quantities are in a proportional relationship from a table, graph, equation, or description.",
        "Identify the constant of proportionality and interpret it in context, including as the slope of a graph.",
        "Solve multi-step real-life problems with positive and negative rational numbers in any form.",
        "Use variables to represent quantities and solve multi-step equations and inequalities, graphing the solution set.",
        "Solve problems involving scale drawings, and construct triangles from given conditions.",
        "Know and use the formulas for the area and circumference of a circle and explain the relationship between them.",
        "Use supplementary, complementary, vertical, and adjacent angle relationships to solve for unknown angles.",
        "Solve area, volume, and surface area problems for two- and three-dimensional objects.",
        "Use random sampling to draw inferences about a population and compare two populations informally.",
        "Investigate chance processes and develop, use, and evaluate probability models.",
    ],
    "units": [
        {"n": 1, "name_en": "Operations with Rational Numbers", "name_hy": "Գործողություններ ռացիոնալ թվերի հետ",
         "lessons": "11–12 lessons",
         "topics": ["Adding integers on a number line and with two-color counters", "The zero pair and additive inverse",
                    "p + q as a directed distance from p", "Subtraction as adding the opposite",
                    "The distance between two rational numbers as |p − q|", "Multiplying integers and why a negative times a negative is positive",
                    "Dividing integers and the placement of the sign in a fraction",
                    "Operations with negative fractions and decimals", "Converting rational numbers to decimals by long division",
                    "Terminating and repeating decimals", "Applying all operations in multi-step real contexts",
                    "Using properties of operations to compute efficiently"],
         "objectives": ["Model integer addition and subtraction on a number line and with counters.",
                        "Explain, using a pattern or the distributive property, why (−3)(−4) = 12.",
                        "Compute fluently with negative fractions and decimals.",
                        "Convert any rational number to a decimal and predict whether it terminates or repeats."],
         "mastery": ["Computes with rational numbers at 90% accuracy across all four operations.",
                     "Produces a justification for the negative-times-negative rule that does not rely on 'the rule says so'.",
                     "Solves multi-step problems with mixed signs and forms in 8 of 10 trials."],
         "misconceptions": [
             ("Sign rules for addition and multiplication are conflated: −3 + −4 answered as 12 or 7.",
              "Separate the two families explicitly and practice them interleaved rather than in blocks. Blocked practice hides the confusion until the test."),
             ("Subtraction of a negative is left unresolved: 5 − (−3) answered as 2.",
              "Model on a number line as distance and direction, and connect to the real context of removing a debt."),
             ("−3² is evaluated as 9.",
              "The exponent binds tighter than the negation. Contrast −3² and (−3)² deliberately and repeatedly; this error survives into calculus."),
         ],
         "note": "This unit rewards interleaved practice more than any other in the curriculum. Mixed sets of problems from the first week onward produce far better retention than one operation per lesson."},

        {"n": 2, "name_en": "Proportional Relationships", "name_hy": "Համեմատական կախվածություններ",
         "lessons": "10–11 lessons",
         "topics": ["Unit rates with fractional quantities", "Recognizing proportionality in a table",
                    "Recognizing proportionality in a graph: a line through the origin",
                    "Recognizing proportionality in an equation of the form y = kx",
                    "The constant of proportionality and its meaning in context",
                    "Non-proportional linear situations and why they fail the test",
                    "Interpreting the point (1, k) on a proportional graph", "Percent increase and decrease",
                    "Markup, discount, tax, tip, commission, and fees", "Simple interest",
                    "Percent error", "Multi-step percent problems"],
         "objectives": ["Determine whether a relationship is proportional from any of the four representations, and justify.",
                        "Identify the constant of proportionality and state its meaning with units.",
                        "Explain why a graph passing through (0, 5) is not proportional even though it is linear.",
                        "Solve multi-step percent problems including successive increases and decreases."],
         "mastery": ["Classifies relationships as proportional or not, with justification, in 9 of 10 trials.",
                     "Interprets k in context with correct units in 9 of 10 trials.",
                     "Solves multi-step percent problems at 85% accuracy."],
         "misconceptions": [
             ("Any linear relationship is called proportional.",
              "The graph must pass through the origin. Present y = 2x and y = 2x + 3 as tables and graphs side by side in the same lesson."),
             ("A 20% increase followed by a 20% decrease is believed to return to the original.",
              "Compute it. The surprise is pedagogically valuable and makes the multiplicative nature of percent change memorable."),
             ("The constant of proportionality is reported as a bare number with no meaning.",
              "Always require units and a sentence: 'k = 3.5 means the cost is $3.50 per pound.'"),
         ],
         "note": "This unit *is* slope, one year early and in a friendlier setting. Say so out loud in the final lesson — the connection to Grade 8 and Algebra I should be made explicit, not discovered later."},

        {"n": 3, "name_en": "Expressions, Equations, and Inequalities", "name_hy": "Արտահայտություններ, հավասարումներ և անհավասարումներ",
         "lessons": "10–11 lessons",
         "topics": ["Adding, subtracting, factoring, and expanding linear expressions with rational coefficients",
                    "Rewriting an expression to reveal how quantities are related",
                    "Solving two-step equations of the form px + q = r", "Solving equations of the form p(x + q) = r",
                    "Comparing arithmetic and algebraic solution paths", "Solving equations with variables on both sides",
                    "Equations with no solution or infinitely many solutions", "Solving two-step inequalities",
                    "Reversing the inequality symbol when multiplying or dividing by a negative",
                    "Graphing inequality solution sets", "Interpreting an inequality solution in context",
                    "Writing equations and inequalities from word problems"],
         "objectives": ["Solve multi-step equations with rational coefficients and check the solution.",
                        "Explain why the inequality symbol reverses when both sides are multiplied by a negative.",
                        "Write an equation or inequality modelling a real situation and interpret the solution in context.",
                        "Recognize an equation with no solution and explain what that means."],
         "mastery": ["Solves multi-step equations at 90% accuracy with work shown.",
                     "Solves and graphs inequalities correctly in 9 of 10 trials, including sign reversal.",
                     "Translates word problems into equations correctly in 8 of 10 trials."],
         "misconceptions": [
             ("The inequality symbol is not reversed when dividing by a negative.",
              "Demonstrate with numbers: 4 > 2, but −4 < −2. Have the student verify a solution by substitution — a wrong direction fails the check immediately."),
             ("Only one side of the equation is operated on.",
              "The balance metaphor. Require the operation to be written under both sides explicitly for the first two weeks."),
             ("The distributive property is applied to only the first term inside the parentheses.",
              "Arrows drawn from the multiplier to every term. Return to the area model from Grade 3 if the error persists."),
         ],
         "note": "Requiring the student to check every solution by substitution is the highest-value habit in this unit. It converts equation-solving from a ritual into a verifiable claim, and it catches the majority of sign errors without teacher intervention."},

        {"n": 4, "name_en": "Geometry: Angles, Circles, and Scale", "name_hy": "Երկրաչափություն. անկյուններ, շրջանագծեր, մասշտաբ",
         "lessons": "10–11 lessons",
         "topics": ["Scale drawings and computing actual lengths and areas from a scale",
                    "How area scales with the square of the scale factor", "Reproducing a scale drawing at a different scale",
                    "Constructing triangles from three given measures with ruler and protractor",
                    "Conditions determining a unique triangle, many triangles, or no triangle",
                    "Cross-sections of right rectangular prisms and pyramids", "The circle: radius, diameter, chord, circumference",
                    "The relationship between circumference and diameter, and the meaning of π",
                    "Area of a circle and an informal derivation of the formula",
                    "Supplementary, complementary, vertical, and adjacent angles",
                    "Solving for unknown angles with an equation", "Area, volume, and surface area in composite real objects"],
         "objectives": ["Compute an actual length and an actual area from a scale drawing.",
                        "Determine from three given measures whether a unique triangle exists.",
                        "Explain where the formula A = πr² comes from using the rearranged-sectors argument.",
                        "Write and solve an equation for an unknown angle using a stated angle relationship."],
         "mastery": ["Solves scale problems including area scaling correctly in 8 of 10 trials.",
                     "Computes circumference and area of circles at 90% accuracy with correct units.",
                     "Solves unknown-angle problems by writing an equation in 9 of 10 trials."],
         "misconceptions": [
             ("Area is scaled by the same factor as length.",
              "Draw a 2 × 3 rectangle and its double. Count squares. The factor-of-four result must be seen, not asserted."),
             ("Circumference and area formulas are interchanged.",
              "Attach units to the formulas: circumference is a length (one dimension, one r), area is square units (two dimensions, r²). The units make the formula self-identifying."),
             ("Vertical angles are assumed to be supplementary.",
              "Draw and measure. Vertical angles are equal; adjacent angles on a line are supplementary. Have the student mark both on the same diagram."),
         ],
         "note": "The unknown-angle problems in this unit are the student's first taste of geometric proof: a diagram, a stated relationship, an equation, a justified conclusion. Require the reason to be written next to each step."},

        {"n": 5, "name_en": "Statistics: Sampling and Inference", "name_hy": "Վիճակագրություն. ընտրանք և եզրակացություն",
         "lessons": "7–8 lessons",
         "topics": ["Populations and samples", "Why a sample must be random to be representative",
                    "Identifying sources of bias in a sampling method", "Estimating a population characteristic from a sample",
                    "Variation among samples from the same population", "Simulating repeated sampling to see the variation",
                    "Comparing two populations using centers and spreads",
                    "Expressing a difference in centers as a multiple of the variability",
                    "Drawing an informal comparative inference and stating its limits"],
         "objectives": ["Explain why random selection is required for a sample to support an inference.",
                        "Identify the bias in a described sampling method and propose a better one.",
                        "Estimate a population mean or proportion from a sample and describe the uncertainty.",
                        "Compare two data distributions and state a defensible informal conclusion."],
         "mastery": ["Identifies sampling bias correctly in 8 of 10 described scenarios.",
                     "Produces a reasonable population estimate with a statement of uncertainty.",
                     "Writes a comparative inference that references both center and spread."],
         "misconceptions": [
             ("A large sample is assumed to be representative regardless of how it was selected.",
              "Size does not fix bias. Use a memorable historical example of a large biased sample and let the student diagnose it."),
             ("Two distributions are compared by their means alone.",
              "Require both center and spread in every comparison statement; overlapping distributions with different means may not support a conclusion at all."),
         ],
         "note": "This unit is genuinely the foundation of AP Statistics. The idea that a conclusion about a population carries uncertainty is new and difficult; give it real time rather than treating it as an end-of-year appendix."},

        {"n": 6, "name_en": "Probability", "name_hy": "Հավանականություն",
         "lessons": "8–9 lessons",
         "topics": ["Probability as a number between 0 and 1 and the meaning of the endpoints",
                    "Likely, unlikely, and equally likely events", "Theoretical probability from equally likely outcomes",
                    "Experimental probability from collected data", "The relationship between the two as trials increase",
                    "Developing and evaluating a uniform probability model",
                    "Developing a model from observed frequencies when outcomes are not equally likely",
                    "Compound events and sample spaces", "Organized lists, tables, and tree diagrams",
                    "Probability of a compound event", "Simulation to estimate a compound probability"],
         "objectives": ["Compute theoretical probability from a sample space and experimental probability from data.",
                        "Explain why experimental probability approaches theoretical probability as trials increase.",
                        "Construct a sample space for a compound event with a table or tree diagram.",
                        "Design and run a simulation to estimate a probability that is hard to compute directly."],
         "mastery": ["Computes both probability types correctly in 9 of 10 trials.",
                     "Constructs a correct sample space for a two-stage compound event in 4 of 5 trials.",
                     "Designs a valid simulation for a stated problem."],
         "misconceptions": [
             ("The gambler's fallacy: after four heads, tails is believed more likely.",
              "Coins have no memory. Simulate 200 flips and examine the runs; the data is more persuasive than the explanation."),
             ("An outcome is called 'impossible' when it merely has low probability.",
              "Reserve probability 0 for genuinely impossible events. Precision here matters for all later work."),
             ("Sample spaces for compound events are enumerated unsystematically and come out incomplete.",
              "Require a table or tree every time until the student's lists are reliably exhaustive."),
         ],
         "note": "Simulation is the most valuable technique in this unit and the one most often skipped. A student who can design a simulation understands probability structurally, not just computationally."},
    ],
    "assessment": [
        ("Placement Assessment", "Before enrollment", "Grade 6 ratio reasoning and rational-number ordering; identifies whether cross-multiplication has replaced understanding."),
        ("Unit Check", "End of each unit · 40 min", "Unit mastery criteria plus two items requiring written justification."),
        ("Fluency Probe", "Every 3rd lesson · 5 min", "Rational-number computation, interleaved across all four operations."),
        ("Proportionality Diagnostic", "After Unit 2", "Includes deliberately non-proportional situations; the key predictor of Algebra I readiness."),
        ("Mid-Year Assessment", "After Unit 3", "Cumulative Units 1–3; weighted toward rational numbers and equations."),
        ("End-of-Course Assessment", "After Unit 6", "All course outcomes; determines whether the student proceeds to Grade 8 or directly to Algebra I."),
    ],
    "pacing": [
        ("Standard", "1 lesson/week, 60 min", "Full course in approximately 50–55 weeks."),
        ("Accelerated", "2 lessons/week", "Full course in approximately 28–32 weeks."),
        ("Compacted 7/8", "2 lessons/week", "Grade 7 and Grade 8 compressed for students targeting Algebra I in Grade 8 with a strong Grade 6 profile."),
        ("Intensive / Catch-Up", "2–3 lessons/week", "22–26 weeks with diagnostic-driven ordering."),
        ("Summer Program", "3 lessons/week, 6 weeks", "Rational number operations intensive (Unit 1) or proportional reasoning intensive (Unit 2)."),
    ],
    "homework": (
        "Forty minutes per lesson: seven to ten problems. Practice is deliberately interleaved rather than blocked — "
        "an assignment on multiplying negatives will also contain addition and subtraction problems, because the "
        "confusion between the sign rules only surfaces when the operations are mixed. Every assignment contains at "
        "least one problem asking the student to explain why a stated method works or why a given answer is wrong. "
        "From Unit 3 onward, solutions to equations must be checked by substitution and the check must be shown."
    ),
    "milestones": [
        "Adds, subtracts, multiplies, and divides all rational numbers fluently.",
        "Justifies the sign rules rather than reciting them.",
        "Recognizes proportional relationships in tables, graphs, equations, and descriptions.",
        "Identifies and interprets the constant of proportionality with units.",
        "Solves multi-step percent problems including markup, discount, and interest.",
        "Solves multi-step equations and inequalities with rational coefficients.",
        "Solves scale-drawing problems and understands how area scales.",
        "Knows and can justify the circumference and area formulas for a circle.",
        "Solves unknown-angle problems by writing and solving equations.",
        "Draws informal inferences from random samples and states their limits.",
        "Builds and evaluates probability models and designs simulations.",
        "Completed Grade 7 Mathematics — ready for Grade 8 or Algebra I.",
    ],
    "materials": [
        "Two-color counters and an extended number line for integer operations.",
        "Compass, protractor, and ruler for the geometry unit (physical set at home required).",
        "Circular objects and string for the π investigation.",
        "Random-number generator and simulation tool for the statistics and probability units.",
        "Վարժարան Grade 7 problem bank — approximately 1,400 items with interleaved practice sets built in.",
    ],
})

# ---------------------------------------------------------------- GRADE 8
COURSES.append({
    "code": "MTH-G8",
    "title_en": "Grade 8 Mathematics",
    "title_hy": "Մաթեմատիկա — 8-րդ դասարան",
    "band": BAND, "band_hy": BAND_HY,
    "grade_label": "Grade 8 · typical age 13–14",
    "hours": "84–96 instructional hours (approx. 72 lessons)",
    "prereq": "Grade 7 Mathematics or equivalent: rational number operations, proportional relationships, multi-step equations.",
    "next": "Algebra I (MTH-A1)",
    "description": (
        "Grade 8 is the bridge into formal algebra. The function arrives as an object — a rule assigning exactly "
        "one output to each input — and linear functions are studied through slope, intercepts, and rate of "
        "change. Students solve systems of two linear equations, work with integer exponents and scientific "
        "notation, meet irrational numbers through square roots, prove and apply the Pythagorean theorem, and "
        "study transformations as the basis of congruence and similarity. The year closes with bivariate data "
        "and the line of best fit."
    ),
    "philosophy": (
        "Grade 8 succeeds or fails on the concept of function. Վարժարան teachers introduce functions through "
        "multiple representations from the first lesson and insist on the definitional test — one output per "
        "input — rather than on the vertical line trick alone. Slope is taught as a rate of change with units "
        "attached, not as a memorized fraction of rise over run, because the rate interpretation is the one that "
        "transfers to Algebra I, to Calculus, and to every applied context. Transformations are taught with "
        "actual movement, because congruence defined as 'same shape and size' is a definition that cannot be "
        "used to prove anything."
    ),
    "readiness": [
        ("Recognizes proportional relationships and interprets the constant of proportionality",
         "Grade 8 slope is Grade 7 proportionality generalized; without it, y = mx + b is meaningless."),
        ("Solves multi-step equations with variables on both sides",
         "Prerequisite for systems in Unit 3; a frequent gap."),
        ("Computes fluently with negative rational numbers",
         "Slope calculations with negatives are the largest single source of Grade 8 errors."),
        ("Graphs points in all four quadrants",
         "Prerequisite for every graphing task in the course."),
    ],
    "outcomes": [
        "Know that numbers not rational are irrational, and approximate irrationals on a number line.",
        "Apply properties of integer exponents to generate equivalent numerical expressions.",
        "Use square and cube root symbols to represent and solve equations of the form x² = p and x³ = p.",
        "Use scientific notation to express and compute with very large and very small quantities.",
        "Graph proportional relationships and interpret the unit rate as the slope of the graph.",
        "Derive y = mx + b and explain why the graph of a linear equation is a straight line.",
        "Solve linear equations in one variable, including those with no solution or infinitely many solutions.",
        "Analyze and solve systems of two linear equations graphically, by substitution, and by elimination.",
        "Understand a function as a rule assigning exactly one output to each input, and compare functions across representations.",
        "Construct and interpret a function to model a linear relationship between two quantities.",
        "Describe qualitatively the functional relationship shown by a graph.",
        "Verify experimentally the properties of rotations, reflections, and translations.",
        "Understand congruence and similarity through sequences of transformations.",
        "Explain a proof of the Pythagorean theorem and apply it in two and three dimensions.",
        "Know and use the volume formulas for cones, cylinders, and spheres.",
        "Investigate patterns of association in bivariate data using scatter plots and two-way tables.",
    ],
    "units": [
        {"n": 1, "name_en": "Exponents, Roots, and the Real Numbers", "name_hy": "Աստիճաններ, արմատներ և իրական թվեր",
         "lessons": "10–11 lessons",
         "topics": ["Properties of integer exponents: product, quotient, power, and power of a product",
                    "Zero and negative exponents and why they are defined as they are",
                    "Simplifying expressions with integer exponents", "Square roots and cube roots",
                    "Solving x² = p and x³ = p and the two solutions of the square case",
                    "Perfect squares and perfect cubes", "Rational and irrational numbers",
                    "Why √2 is irrational (an accessible proof)", "Approximating an irrational number to a given precision",
                    "Locating irrationals on the number line and comparing them",
                    "Scientific notation for large and small numbers", "Operating with numbers in scientific notation",
                    "Choosing units appropriate to a magnitude"],
         "objectives": ["Apply exponent properties to simplify an expression with integer exponents.",
                        "Explain why a⁰ = 1 and why a⁻ⁿ = 1/aⁿ, using the quotient property rather than a rule.",
                        "Approximate an irrational number to two decimal places and place it on a number line.",
                        "Multiply and divide numbers in scientific notation and interpret the result in context."],
         "mastery": ["Simplifies integer-exponent expressions at 90% accuracy.",
                     "Justifies the zero and negative exponent definitions from the quotient property.",
                     "Computes in scientific notation correctly in 9 of 10 trials with correct final form."],
         "misconceptions": [
             ("A negative exponent is believed to make the value negative.",
              "It indicates a reciprocal, not a sign. Build the pattern 2³, 2², 2¹, 2⁰, 2⁻¹ downward and let the student see the halving continue."),
             ("Exponents are added when bases are multiplied but bases are also multiplied: 2³ · 2⁴ = 4⁷.",
              "Expand once, fully, as repeated multiplication. The property should be a compression of something the student has written out."),
             ("Every square root is assumed irrational, or √ is assumed to distribute over addition.",
              "Test √(9 + 16) against √9 + √16 with a calculator. A single counterexample settles it permanently."),
         ],
         "note": "The proof that √2 is irrational is worth one full lesson even though no standard requires it. It is most students' first encounter with proof by contradiction, and it is memorable in a way that few Grade 8 lessons are."},

        {"n": 2, "name_en": "Linear Equations and Slope", "name_hy": "Գծային հավասարումներ և անկյունային գործակից",
         "lessons": "10–11 lessons",
         "topics": ["Graphing proportional relationships and identifying the unit rate as slope",
                    "Comparing two proportional relationships in different representations",
                    "Slope as a rate of change with units", "Similar triangles and why slope is constant along a line",
                    "Deriving y = mx for a line through the origin and y = mx + b generally",
                    "Slope from two points, from a graph, from a table, and from an equation",
                    "Positive, negative, zero, and undefined slope", "x- and y-intercepts and their meaning in context",
                    "Solving linear equations with variables on both sides", "Equations with no solution and with infinitely many solutions",
                    "Equations requiring expansion and collection of like terms",
                    "Writing a linear equation from a context and interpreting its parameters"],
         "objectives": ["Compute slope from any representation and state its meaning in context with units.",
                        "Explain, using similar triangles, why the slope of a line is the same everywhere on it.",
                        "Solve linear equations including cases with no solution or infinitely many solutions, and interpret those cases.",
                        "Write an equation modelling a linear situation and interpret m and b in context."],
         "mastery": ["Computes slope correctly from all four representations in 9 of 10 trials.",
                     "Interprets slope and intercept in context with correct units in 9 of 10 trials.",
                     "Solves linear equations at 90% accuracy, correctly identifying special cases."],
         "misconceptions": [
             ("Slope is computed as run over rise, or the subtraction order is inconsistent between numerator and denominator.",
              "Label both points and write the formula with subscripts every time. Requiring the labels for two weeks eliminates most of these errors permanently."),
             ("A negative slope is confused with a line in a particular position rather than with a decreasing relationship.",
              "Always describe slope in words first — 'for every one unit right, down two' — before writing the number."),
             ("An equation with no solution is answered as 'x = 0'.",
              "0 = 5 is a false statement, not a value of x. Contrast it with 0 = 0 in the same lesson."),
         ],
         "note": "The similar-triangles argument for constant slope is the conceptual heart of the unit and is routinely skipped. It is what makes slope a property of the *line* rather than of the two points chosen, and it is required for anything later to make sense."},

        {"n": 3, "name_en": "Systems of Linear Equations", "name_hy": "Գծային հավասարումների համակարգեր",
         "lessons": "8–9 lessons",
         "topics": ["What a solution to a system means", "Solving a system by graphing and reading the intersection",
                    "The limits of graphical solutions", "Solving by substitution",
                    "Solving by elimination", "Choosing an efficient method for a given system",
                    "Systems with no solution: parallel lines", "Systems with infinitely many solutions: the same line",
                    "Recognizing the special cases from the equations alone",
                    "Writing a system to model a real situation", "Interpreting the solution in context"],
         "objectives": ["Explain that a solution to a system is a point satisfying both equations simultaneously.",
                        "Solve a system by graphing, substitution, and elimination and choose appropriately among them.",
                        "Determine from the equations alone whether a system has zero, one, or infinitely many solutions.",
                        "Write and solve a system modelling a real problem and interpret the answer in context."],
         "mastery": ["Solves systems by all three methods at 90% accuracy.",
                     "Correctly classifies the number of solutions from the equations in 9 of 10 trials.",
                     "Models a real situation with a correct system in 8 of 10 trials."],
         "misconceptions": [
             ("The solution is reported as a single number rather than an ordered pair.",
              "A system in two variables has a two-part answer. Require both coordinates and a check in both equations."),
             ("In elimination, only one side of an equation is multiplied.",
              "The entire equation must be scaled. Write the multiplier outside a bracket enclosing the whole equation."),
             ("Substitution is attempted without first isolating a variable.",
              "Model the decision explicitly: which variable is cheapest to isolate, and why."),
         ],
         "note": "Systems are the first place where a student must choose a method rather than execute the only one available. Spend a lesson purely on method selection — presenting systems and asking only 'which method, and why?' without solving."},

        {"n": 4, "name_en": "Functions", "name_hy": "Ֆունկցիաներ",
         "lessons": "9–10 lessons",
         "topics": ["The definition of a function: exactly one output per input",
                    "Domain and range informally", "Function notation and reading f(x)",
                    "Functions as tables, graphs, equations, and verbal descriptions",
                    "Testing whether a relation is a function in each representation",
                    "Comparing two functions given in different representations",
                    "Linear versus nonlinear functions and how to tell", "Constructing a linear function from two points or from a description",
                    "Interpreting the rate of change and initial value of a linear function",
                    "Describing a graph qualitatively: increasing, decreasing, constant, linear, nonlinear",
                    "Sketching a graph from a verbal description of a situation"],
         "objectives": ["Determine whether a relation is a function from any representation and justify with the definition.",
                        "Interpret f(3) = 7 in the context of a described situation.",
                        "Compare the rates of change of two functions given in different forms.",
                        "Sketch a qualitative graph matching a verbal story and explain each feature."],
         "mastery": ["Applies the function definition correctly in 9 of 10 trials across representations.",
                     "Uses and interprets function notation correctly in 9 of 10 trials.",
                     "Produces a qualitative graph consistent with a given story in 4 of 5 trials."],
         "misconceptions": [
             ("f(x) is read as f times x.",
              "Correct on first sight and every time thereafter. This misreading is fatal in Algebra II and beyond, and it is cheap to prevent now."),
             ("A relation is judged a function by the vertical line test alone, with no reference to the definition.",
              "The test is a consequence of the definition, not a replacement. Require the definitional argument for tables and mappings, where no graph exists."),
             ("Any straight-looking graph is called linear without checking constant rate of change.",
              "Check the table. Constant differences over equal intervals is the criterion."),
         ],
         "note": "Function notation is introduced here deliberately, ahead of many curricula. Students who become comfortable with f(x) in Grade 8 have a substantially easier Algebra I, and the cost of introducing it early is low."},

        {"n": 5, "name_en": "Transformations, Congruence, and Similarity", "name_hy": "Ձևափոխություններ, համընկնում և նմանություն",
         "lessons": "9–10 lessons",
         "topics": ["Translations, reflections, and rotations as motions of the plane",
                    "Properties preserved by rigid motions: length, angle measure, parallelism",
                    "Describing a transformation with coordinates", "Composing transformations",
                    "Congruence defined as the existence of a sequence of rigid motions",
                    "Describing the sequence that maps one figure onto a congruent one",
                    "Dilations and the scale factor", "Similarity defined via dilation and rigid motions",
                    "Similar triangles and the angle-angle criterion",
                    "The angle sum of a triangle established by a parallel-line argument",
                    "The exterior angle theorem", "Angles formed by parallel lines cut by a transversal"],
         "objectives": ["Perform each rigid motion on the coordinate plane and state the coordinate rule.",
                        "Describe a specific sequence of transformations mapping one figure onto another.",
                        "Explain why the angle-angle criterion establishes similarity.",
                        "Prove informally that the angles of a triangle sum to 180° using parallel lines."],
         "mastery": ["Performs and describes all three rigid motions accurately in 9 of 10 trials.",
                     "Produces a valid transformation sequence for a congruence in 4 of 5 trials.",
                     "Applies the AA criterion and parallel-line angle relationships at 85% accuracy."],
         "misconceptions": [
             ("Rotation direction and centre are ignored.",
              "Every rotation requires a centre, an angle, and a direction. Require all three to be stated; a rotation without a centre is not a described transformation."),
             ("Congruence is defined as 'same shape and size', which cannot support an argument.",
              "Define it as the existence of a sequence of rigid motions. This is the definition that makes proof possible in Geometry."),
             ("Similar figures are believed to have proportional angles as well as sides.",
              "Angles are preserved exactly under dilation; only lengths scale. Measure to confirm."),
         ],
         "note": "This unit is the direct foundation of the transformational approach used in the Geometry course. The vocabulary and the habit of describing a specific mapping — not merely asserting congruence — should be established here."},

        {"n": 6, "name_en": "Pythagorean Theorem, Volume, and Bivariate Data", "name_hy": "Պյութագորասի թեորեմ, ծավալ և երկչափ տվյալներ",
         "lessons": "10–11 lessons",
         "topics": ["A proof of the Pythagorean theorem using area", "The converse and its use in testing for right angles",
                    "Applying the theorem in two dimensions", "Applying the theorem in three dimensions",
                    "Distance between two points on the coordinate plane",
                    "Volume of cylinders, cones, and spheres", "Relationships among the three volume formulas",
                    "Solving real problems with volume", "Scatter plots for bivariate measurement data",
                    "Describing association: clustering, outliers, linearity, direction, strength",
                    "Fitting a straight line informally and assessing the fit",
                    "Interpreting the slope and intercept of a fitted line in context",
                    "Two-way tables for bivariate categorical data", "Relative frequencies and evidence of association"],
         "objectives": ["Explain a proof of the Pythagorean theorem, not merely apply the formula.",
                        "Use the converse to determine whether a triangle is right-angled.",
                        "Compute the volume of a cone, cylinder, or sphere and explain the relationship among the formulas.",
                        "Fit a line to a scatter plot and interpret its slope and intercept in context.",
                        "Construct a two-way table and use relative frequencies to describe association."],
         "mastery": ["Applies the theorem in two and three dimensions at 90% accuracy.",
                     "Computes volumes of all three solids correctly with units in 9 of 10 trials.",
                     "Interprets a fitted line's slope in context with correct units in 4 of 5 trials."],
         "misconceptions": [
             ("The hypotenuse is not identified before the theorem is applied.",
              "Mark the right angle and the side opposite it before writing anything. Most errors are identification errors, not computation errors."),
             ("The cone volume formula is applied without the factor of one third.",
              "Demonstrate by filling a cone into a cylinder of the same base and height three times. The physical demonstration prevents the error."),
             ("Correlation is interpreted as causation.",
              "Introduce a spurious-correlation example and require the student to propose an alternative explanation. This habit matters far beyond mathematics."),
         ],
         "note": "The distance formula should be derived here as the Pythagorean theorem applied to a coordinate grid, never presented as a separate formula to memorize. Students who see the derivation never forget it."},
    ],
    "assessment": [
        ("Placement Assessment", "Before enrollment", "Grade 7 proportionality and equation-solving; determines whether the student should instead begin Algebra I directly."),
        ("Unit Check", "End of each unit · 45 min", "Unit mastery criteria plus two items requiring justification or interpretation."),
        ("Fluency Probe", "Every 3rd lesson · 5 min", "Rational-number computation and slope calculation."),
        ("Function Concept Diagnostic", "After Unit 4", "Definition, notation, and multiple representations; the key predictor of Algebra I success."),
        ("Mid-Year Assessment", "After Unit 3", "Cumulative Units 1–3; weighted toward linear equations and slope."),
        ("End-of-Course Assessment", "After Unit 6", "All course outcomes; determines Algebra I placement and pacing."),
    ],
    "pacing": [
        ("Standard", "1 lesson/week, 60 min", "Full course in approximately 50–55 weeks."),
        ("Accelerated", "2 lessons/week", "Full course in approximately 28–32 weeks."),
        ("Algebra I Bridge", "2 lessons/week, 12 weeks", "Units 2, 3, and 4 only — for students entering Algebra I with gaps in linear reasoning."),
        ("Intensive / Catch-Up", "2–3 lessons/week", "22–26 weeks with diagnostic-driven ordering."),
        ("Summer Program", "3 lessons/week, 6 weeks", "Linear functions intensive (Units 2 and 4)."),
    ],
    "homework": (
        "Forty to fifty minutes per lesson: eight to twelve problems including at least two multi-step applied "
        "problems and two cumulative review items. From Unit 2 onward, every problem involving slope or a linear "
        "model must include a sentence interpreting the answer in context with units — a bare number is marked "
        "incomplete. Students maintain a running error log of their own recurring mistakes, reviewed with the "
        "teacher at each unit boundary; this single practice measurably reduces repeated errors."
    ),
    "milestones": [
        "Applies integer exponent properties and justifies zero and negative exponents.",
        "Distinguishes rational from irrational numbers and approximates irrationals.",
        "Computes and interprets slope as a rate of change with units.",
        "Derives and uses y = mx + b and explains why linear graphs are straight.",
        "Solves linear equations including no-solution and infinite-solution cases.",
        "Solves systems by graphing, substitution, and elimination and chooses appropriately.",
        "Understands the definition of a function and uses function notation correctly.",
        "Compares functions across tables, graphs, equations, and descriptions.",
        "Describes congruence and similarity through sequences of transformations.",
        "Explains a proof of the Pythagorean theorem and applies it in 2-D and 3-D.",
        "Finds volumes of cylinders, cones, and spheres.",
        "Fits and interprets a line on a scatter plot and reads a two-way table.",
        "Completed Grade 8 Mathematics — ready for Algebra I.",
    ],
    "materials": [
        "Dynamic geometry software for the transformations unit (teacher-shared).",
        "Graphing tool for functions and systems; scientific calculator.",
        "Physical models of a cone and cylinder with matching base and height for the volume demonstration.",
        "Compass, protractor, and ruler.",
        "Վարժարան Grade 8 problem bank — approximately 1,500 items with a 250-item linear functions sub-bank.",
    ],
})

# ---------------------------------------------------------------- PRE-ALGEBRA
COURSES.append({
    "code": "MTH-PA",
    "title_en": "Pre-Algebra",
    "title_hy": "Նախահանրահաշիվ",
    "band": BAND, "band_hy": BAND_HY,
    "grade_label": "Bridge course · typically Grades 7–9",
    "hours": "60–72 instructional hours (approx. 54 lessons)",
    "prereq": "Grade 6 Mathematics or equivalent, or placement by assessment. Suitable for any student entering Algebra I with gaps.",
    "next": "Algebra I (MTH-A1)",
    "description": (
        "Pre-Algebra is a bridge course, not a grade level. It exists for the student who has finished middle "
        "school arithmetic but is not yet ready for the pace and abstraction of Algebra I — and for the student "
        "who is entering Algebra I from a different school system and needs the gaps found by the placement "
        "assessment closed efficiently. The course consolidates rational-number fluency, proportional reasoning, "
        "and the language of algebra, then takes the student through linear equations and functions to the "
        "threshold of Algebra I. It is deliberately narrower and deeper than a grade-level course."
    ),
    "philosophy": (
        "Most students who struggle in Algebra I do not struggle with algebra. They struggle with negative "
        "numbers, with fractions, with the meaning of the equals sign, and with reading a symbol as a quantity. "
        "Վարժարան designed this course around that observation: it spends its time on the small number of ideas "
        "that actually cause Algebra I failure, and it does so with a diagnostic-first structure. The placement "
        "assessment determines which units a given student needs, and a student with a clean profile in a given "
        "area may skip that unit entirely. Nothing here is taught for completeness; everything is taught because "
        "its absence causes a specific downstream failure."
    ),
    "readiness": [
        ("Performs the four operations with fractions and decimals",
         "If absent, begin with Unit 1 in full; otherwise Unit 1 may be compressed or skipped."),
        ("Orders negative numbers and understands absolute value",
         "Determines whether Unit 2 is needed at full length."),
        ("Solves a one-step equation and checks by substitution",
         "Determines the entry point into Unit 4."),
        ("Interprets a ratio or a rate in context",
         "Determines whether Unit 3 is needed; the most common gap in students arriving from other systems."),
    ],
    "outcomes": [
        "Compute fluently and confidently with all rational numbers in fraction, decimal, and percent form.",
        "Apply the order of operations and the properties of operations correctly and flexibly.",
        "Work with integer exponents, square roots, and scientific notation.",
        "Reason proportionally and solve percent, rate, and scale problems.",
        "Read, write, and manipulate algebraic expressions using correct vocabulary.",
        "Solve multi-step linear equations and inequalities, including variables on both sides.",
        "Translate between verbal situations and algebraic models in both directions.",
        "Understand the function concept and use function notation.",
        "Graph linear relationships and interpret slope and intercept in context.",
        "Apply the Pythagorean theorem and compute area, surface area, and volume.",
        "Approach an unfamiliar problem with a deliberate strategy rather than by guessing at an operation.",
    ],
    "units": [
        {"n": 1, "name_en": "Rational Number Fluency", "name_hy": "Ռացիոնալ թվերի սահուն կիրառում",
         "lessons": "8–9 lessons",
         "topics": ["The four operations with fractions, revisited for fluency and speed",
                    "The four operations with decimals", "Converting among fractions, decimals, and percents",
                    "Order of operations with nested grouping and exponents",
                    "Commutative, associative, distributive, identity, and inverse properties by name",
                    "Using properties to compute efficiently rather than mechanically",
                    "Estimation and reasonableness checking", "GCF, LCM, and prime factorization",
                    "Choosing the most convenient form of a number for a given task"],
         "objectives": ["Compute with any rational number in any form, choosing the most convenient representation.",
                        "Name the property justifying each step of a computation.",
                        "Estimate before computing and use the estimate to detect errors.",
                        "Convert fluently among fraction, decimal, and percent forms."],
         "mastery": ["Computes with rational numbers at 92% accuracy across all forms.",
                     "Names the property used in 8 of 10 prompted steps.",
                     "Detects a planted error by estimation in 4 of 5 trials."],
         "misconceptions": [
             ("Order of operations is applied as a rigid left-to-right sequence of the letters in a mnemonic.",
              "Multiplication and division share a level and are performed left to right, as do addition and subtraction. Use contrasting pairs such as 8 ÷ 4 × 2 until the level structure is clear."),
             ("Percent is treated as a separate number type rather than a form of a rational number.",
              "Convert in both directions in the same lesson and require the student to state which form is easiest for the task at hand."),
         ],
         "note": "This unit is skipped entirely for students whose placement assessment shows clean rational-number fluency. It exists to be diagnostic, not obligatory."},

        {"n": 2, "name_en": "Integers, Exponents, and Roots", "name_hy": "Ամբողջ թվեր, աստիճաններ և արմատներ",
         "lessons": "8–9 lessons",
         "topics": ["The number line extended and the meaning of a negative quantity",
                    "Adding and subtracting integers with models", "Subtraction as adding the opposite",
                    "Multiplying and dividing integers and justifying the sign rules",
                    "Operations with negative fractions and decimals", "Absolute value as distance",
                    "Integer exponents and the exponent properties", "Zero and negative exponents",
                    "Square roots and cube roots; perfect squares to 225", "Estimating a square root between consecutive integers",
                    "Rational and irrational numbers", "Scientific notation and computing with it"],
         "objectives": ["Compute with negative numbers in all forms fluently.",
                        "Justify the sign rules from patterns or from the distributive property.",
                        "Simplify expressions using integer exponent properties.",
                        "Estimate a square root and place an irrational number on a number line."],
         "mastery": ["Computes with negatives at 92% accuracy on interleaved problem sets.",
                     "Simplifies exponent expressions at 90% accuracy.",
                     "Estimates square roots to the nearest tenth in 4 of 5 trials."],
         "misconceptions": [
             ("Sign errors appear in long computations even when the rules are known in isolation.",
              "This is a working-memory problem, not a knowledge problem. Require intermediate steps to be written; forbid mental multi-step sign handling until accuracy is stable."),
             ("−x is assumed to be a negative number.",
              "It is the opposite of x, which is positive when x is negative. Substitute x = −3 explicitly. This misconception causes real damage in Algebra I."),
         ],
         "note": "Interleaved practice is essential here. A student who scores well on a page of multiplication-only sign problems has not demonstrated anything; mix the operations from the first assignment."},

        {"n": 3, "name_en": "Ratio, Proportion, and Percent", "name_hy": "Հարաբերություն, համեմատություն և տոկոս",
         "lessons": "8–9 lessons",
         "topics": ["Ratios, rates, and unit rates", "Ratio tables, tape diagrams, and double number lines",
                    "Proportional relationships in tables, graphs, equations, and descriptions",
                    "The constant of proportionality and its interpretation",
                    "Solving proportions, with cross-multiplication introduced last and justified",
                    "Non-proportional situations and how to recognize them",
                    "Percent of a number; finding the whole; finding the percent",
                    "Percent increase and decrease; markup, discount, tax, tip", "Simple interest",
                    "Scale drawings, maps, and models", "Unit conversion by rate reasoning"],
         "objectives": ["Decide whether a relationship is proportional and justify from any representation.",
                        "Solve a proportion by scaling, by unit rate, and by cross-multiplication, and explain why all three work.",
                        "Solve multi-step percent problems including successive changes.",
                        "Convert units within and between systems by multiplying by rates equal to one."],
         "mastery": ["Classifies relationships correctly in 9 of 10 trials with justification.",
                     "Solves multi-step percent problems at 88% accuracy.",
                     "Performs multi-step unit conversions correctly in 8 of 10 trials."],
         "misconceptions": [
             ("Cross-multiplication is applied to any pair of fractions, including in addition problems.",
              "It is a technique for solving a proportion, not a general operation. Introduce it only after scaling and unit-rate methods are secure."),
             ("A proportion is set up with mismatched units across the two ratios.",
              "Label every quantity with its unit inside the proportion. Mismatched labels reveal the setup error before any arithmetic occurs."),
         ],
         "note": "Proportional reasoning is the most transferable idea in this course and the gap most often found in students arriving from other school systems. Even a strong placement profile warrants a diagnostic pass through this unit."},

        {"n": 4, "name_en": "The Language of Algebra", "name_hy": "Հանրահաշվի լեզուն",
         "lessons": "9–10 lessons",
         "topics": ["Variables as quantities that vary, and as unknowns to be found",
                    "Vocabulary: term, coefficient, constant, factor, like terms, expression, equation",
                    "Translating verbal phrases into expressions and expressions into words",
                    "Evaluating expressions at given values, including negatives",
                    "Combining like terms", "The distributive property with variables, including negative multipliers",
                    "Expanding and factoring simple linear expressions",
                    "Determining whether two expressions are equivalent", "The meaning of a solution to an equation",
                    "Solving one-step and two-step equations", "Solving equations with variables on both sides",
                    "Equations requiring expansion first", "Checking solutions by substitution",
                    "Solving and graphing linear inequalities", "Reversing the inequality when multiplying by a negative",
                    "Writing equations and inequalities from word problems"],
         "objectives": ["Use algebraic vocabulary precisely in speech and in writing.",
                        "Translate fluently in both directions between verbal descriptions and algebraic symbols.",
                        "Solve multi-step linear equations and inequalities and verify solutions.",
                        "Write an equation or inequality modelling a described situation and interpret the solution."],
         "mastery": ["Solves multi-step equations at 90% accuracy with checking shown.",
                     "Translates in both directions correctly in 9 of 10 trials.",
                     "Uses vocabulary correctly without prompting in 8 of 10 observed instances."],
         "misconceptions": [
             ("A variable is treated as a label for an object rather than as a number.",
              "The single most damaging misconception in early algebra. Insist that the variable represents *the number of* things, and substitute values often to keep it numeric."),
             ("Like terms are combined incorrectly: 3x + 2 becomes 5x.",
              "Terms with different variable parts cannot be combined. Use a concrete analogy — three x's and two units are not five of anything — and substitute a value to demonstrate."),
             ("Distributing a negative multiplier changes only the first sign.",
              "Write the multiplier with its sign attached and draw arrows to every term. Then check by substituting a value into both forms."),
         ],
         "note": "This is the core unit of the course and should receive the most time. A student who leaves it with precise vocabulary and reliable equation-solving will pass Algebra I; one who does not, will not, regardless of what else they know."},

        {"n": 5, "name_en": "Linear Relationships and Functions", "name_hy": "Գծային կախվածություններ և ֆունկցիաներ",
         "lessons": "8–9 lessons",
         "topics": ["The coordinate plane and graphing ordered pairs in four quadrants",
                    "Tables, graphs, and equations as three views of one relationship",
                    "The definition of a function and testing for it", "Function notation and reading f(x)",
                    "Rate of change and slope, with units", "Slope from two points, a graph, a table, and an equation",
                    "Intercepts and their meaning in context", "Slope-intercept form and graphing from it",
                    "Writing the equation of a line from a graph, a table, or a description",
                    "Linear versus nonlinear relationships", "Systems of two linear equations by graphing and substitution",
                    "Interpreting a solution in context"],
         "objectives": ["Move fluently among table, graph, and equation for a linear relationship.",
                        "Apply the definition of a function and use function notation correctly.",
                        "Compute slope from any representation and interpret it with units in context.",
                        "Write the equation of a line from any adequate description and solve a simple system."],
         "mastery": ["Moves among representations correctly in 9 of 10 tasks.",
                     "Interprets slope and intercept in context with units in 9 of 10 trials.",
                     "Solves systems by graphing and substitution at 88% accuracy."],
         "misconceptions": [
             ("Slope is memorized as rise over run with no meaning attached.",
              "Require a contextual sentence with units for every slope computed. A number with no interpretation is marked incomplete."),
             ("f(x) is read as multiplication.",
              "Correct immediately and permanently. The cost of allowing this to persist is very high in Algebra II."),
         ],
         "note": "Ending the course with functions rather than with geometry is deliberate: it hands the student directly to Algebra I Unit 1 with the right vocabulary already in place."},

        {"n": 6, "name_en": "Geometry and Measurement Essentials", "name_hy": "Երկրաչափության և չափման հիմունքներ",
         "lessons": "6–7 lessons",
         "topics": ["Angle relationships: complementary, supplementary, vertical, adjacent",
                    "Angles formed by parallel lines and a transversal", "Triangle angle sum and the exterior angle theorem",
                    "The Pythagorean theorem, its converse, and applications",
                    "Distance between two points on the coordinate plane",
                    "Area and perimeter of triangles, quadrilaterals, and circles",
                    "Area of composite figures", "Surface area and volume of prisms, cylinders, cones, and spheres",
                    "Similar figures and scale factor; how area and volume scale",
                    "Unit analysis and dimensional reasoning"],
         "objectives": ["Solve for unknown angles by writing and solving an equation with a stated reason.",
                        "Apply the Pythagorean theorem in two and three dimensions and derive the distance formula.",
                        "Compute area, surface area, and volume for standard figures with correct units.",
                        "Explain how area and volume scale under a dilation."],
         "mastery": ["Solves unknown-angle problems with reasons in 9 of 10 trials.",
                     "Applies the Pythagorean theorem at 90% accuracy.",
                     "Computes area, surface area, and volume with correct units in 9 of 10 trials."],
         "misconceptions": [
             ("Formulas are memorized without dimensional understanding, so area formulas are used for volume.",
              "Reason from units. A volume must produce cubic units; a formula that cannot is the wrong formula."),
             ("Under a scale factor of 3, volume is assumed to triple.",
              "Volume scales by the cube of the factor. Build a 1-cube and a 3-cube from unit cubes and count."),
         ],
         "note": "Unit analysis introduced here is one of the most powerful error-catching tools a student can own, and it costs almost nothing to teach. Require units on every answer for the remainder of the course."},
    ],
    "assessment": [
        ("Diagnostic Placement Assessment", "Before enrollment", "Comprehensive: determines which units the student needs and in what order. Units with a clean profile may be skipped entirely."),
        ("Unit Check", "End of each unit · 40 min", "Unit mastery criteria; a failed check returns the student to targeted lessons rather than advancing."),
        ("Fluency Probe", "Every 2nd lesson · 5 min", "Rational-number and integer computation, interleaved."),
        ("Algebra Readiness Assessment", "After Unit 4", "Equation-solving, translation, and vocabulary; the gate for Algebra I entry."),
        ("End-of-Course Assessment", "After Unit 6", "All course outcomes; produces a formal Algebra I readiness recommendation for the parent."),
    ],
    "pacing": [
        ("Standard", "1 lesson/week, 60 min", "Full course in approximately 40–45 weeks."),
        ("Accelerated", "2 lessons/week", "Full course in approximately 22–26 weeks."),
        ("Targeted (diagnostic-driven)", "2 lessons/week", "Only the units indicated by the placement assessment; typically 10–20 weeks."),
        ("Summer Algebra Bridge", "3 lessons/week, 8 weeks", "Units 2, 3, and 4 — designed for students entering Algebra I in the autumn."),
    ],
    "homework": (
        "Thirty-five to forty-five minutes per lesson. Assignments are interleaved by design: each contains current "
        "content, one problem from the previous unit, and one from an earlier one. Every equation solved must be "
        "checked by substitution, and every applied answer must carry units and a sentence of interpretation. "
        "Students maintain an error log; because this course exists to close specific gaps, knowing precisely which "
        "errors recur is more valuable here than in any other course in the catalog."
    ),
    "milestones": [
        "Computes fluently with all rational numbers in every form.",
        "Justifies the integer sign rules rather than reciting them.",
        "Applies exponent properties and estimates square roots.",
        "Recognizes proportional relationships and solves multi-step percent problems.",
        "Uses algebraic vocabulary precisely.",
        "Translates fluently between words and algebraic symbols.",
        "Solves multi-step equations and inequalities with variables on both sides.",
        "Understands the function concept and uses function notation.",
        "Computes and interprets slope with units in context.",
        "Applies the Pythagorean theorem and computes area, surface area, and volume.",
        "Completed Pre-Algebra — formally assessed as ready for Algebra I.",
    ],
    "materials": [
        "Scientific calculator (graphing calculator not required for this course).",
        "Two-color counters and an extended number line for integer work.",
        "Graphing tool for the linear relationships unit.",
        "Compass, protractor, and ruler.",
        "Վարժարան Pre-Algebra problem bank — approximately 1,100 items organized by diagnostic gap rather than by lesson.",
    ],
})
