/**
 * `AuditStore` is the append-only port every function in this package is written against.
 * Deliberately: no `updateEvent`, no `deleteEvent`, no method of any kind that could mutate or
 * remove a row once inserted. That omission is itself the guarantee spec §12.5 asks for ("audit
 * logs are append-only to application users") — nothing in this package can call a method that
 * does not exist, regardless of role or actor. Postgres additionally enforces this with a
 * `BEFORE UPDATE OR DELETE` trigger (`packages/db/migrations/0001_audit_events_immutable.sql`),
 * so the guarantee holds even against a client that bypasses this package entirely.
 */
export interface AuditEventRecord {
  id: string;
  /** `null` for system/automated events with no human actor (e.g. a scheduled retention job). */
  actorUserId: string | null;
  action: string;
  resourceType: string;
  resourceId: string | null;
  reason: string | null;
  previousValue: unknown;
  newValue: unknown;
  ipAddress: string | null;
  createdAt: Date;
}

/** What `AuditStore.insertEvent` accepts — the id is generated by the caller (`recordAudit`), never by the store. */
export interface InsertAuditEventValues {
  id: string;
  actorUserId: string | null;
  action: string;
  resourceType: string;
  resourceId?: string | null;
  reason?: string | null;
  previousValue?: unknown;
  newValue?: unknown;
  ipAddress?: string | null;
}

export interface AdminAccessReasonRecord {
  id: string;
  adminUserId: string;
  targetEntityType: string;
  targetEntityId: string;
  reason: string;
  accessedAt: Date;
}

export interface InsertAdminAccessReasonValues {
  id: string;
  adminUserId: string;
  targetEntityType: string;
  targetEntityId: string;
  reason: string;
  accessedAt?: Date;
}

export interface AuditQueryFilters {
  actorUserId?: string;
  action?: string;
  resourceType?: string;
  resourceId?: string;
  /** Inclusive lower bound on `createdAt`. */
  from?: Date;
  /** Inclusive upper bound on `createdAt`. */
  to?: Date;
  /** Opaque cursor from a previous page's `nextCursor` — never construct one by hand. */
  cursor?: string;
  /** Defaults to 50, capped at 200. */
  limit?: number;
}

export interface AuditQueryPage {
  items: AuditEventRecord[];
  /** `null` once the last page has been reached. */
  nextCursor: string | null;
}

export interface AuditStore {
  /**
   * Runs `operation` against a store bound to one transaction. Implementations that are already
   * inside a transaction (nested calls) reuse it rather than opening a second one, mirroring
   * every other domain module's `Database.transaction` contract in this codebase.
   */
  transaction<T>(operation: (store: AuditStore) => Promise<T>): Promise<T>;
  insertEvent(values: InsertAuditEventValues): Promise<AuditEventRecord>;
  findEventById(id: string): Promise<AuditEventRecord | null>;
  /**
   * The most recent `approval.decided` event whose `resourceId` is `approvalRequestId`, or `null`
   * if that request hasn't been decided yet. Used by `approveHighRiskAction` to reject a second
   * decision on an already-resolved request.
   */
  findDecisionForRequest(approvalRequestId: string): Promise<AuditEventRecord | null>;
  queryEvents(filters: AuditQueryFilters): Promise<AuditQueryPage>;
  insertAdminAccessReason(values: InsertAdminAccessReasonValues): Promise<AdminAccessReasonRecord>;
}
