import type { Locale } from "@app/i18n/config";

const en = {
  eyebrow: "No-cost first step",
  title: "Let’s understand what your learner needs.",
  intro:
    "Tell us a little about the learner, their goals, and their schedule. We’ll help identify a suitable subject, level, tutor, and lesson format.",
  assurances: ["Takes about 2 minutes", "No payment to submit", "No obligation", "Parent or guardian details only"],
  stepLabel: (step: number) => `Step ${step} of 5`,
  reviewLabel: "Review request",
  steps: ["Learning need", "Learner level", "Lesson format", "Schedule", "Parent contact"],
  back: "Back",
  edit: "Edit",
  continue: ["Choose learner level", "Choose lesson format", "Continue to schedule", "Add parent contact", "Review request"],
  learning: {
    title: "What would you like help with?",
    hint: "Choose the closest option. You can change it later.",
    subject: "Subject or learning path",
    subjects: {
      mathematics: "Mathematics",
      armenian: "Armenian language & culture",
      "group-lessons": "Group lessons",
      "not-sure": "Not sure yet",
    },
    goal: "What is the main goal?",
    goals: {
      "catch-up": "Catch up",
      "stay-on-track": "Stay on track",
      "move-ahead": "Move ahead",
      homework: "Homework support",
      "exam-prep": "Prepare for an exam",
      confidence: "Build confidence",
      "problem-solving": "Improve problem-solving",
      "armenian-connection": "Connect with Armenian language and culture",
      "not-sure": "Not sure yet",
    },
  },
  learner: {
    title: "Tell us about the learner.",
    hint: "No learner name or date of birth is needed.",
    grade: "Grade, course, or learning path",
    select: "Choose an option",
    mathLevels: ["Grade 1", "Grade 2", "Grade 3", "Grade 4", "Grade 5", "Grade 6", "Grade 7", "Grade 8", "Pre-Algebra", "Algebra I", "Geometry", "Algebra II", "Precalculus", "Not sure"],
    armenianLevels: ["Complete beginner", "Understands some Armenian", "Speaking development", "Reading and writing", "Grammar and academic Armenian", "Armenian culture and heritage", "Advanced Armenian", "Not sure"],
    generalLevels: ["Primary school", "Middle school", "High school", "Adult learner", "Not sure"],
    currentLevel: "Current level (optional)",
    currentLevels: ["Needs foundation support", "Slightly below current grade", "At current grade level", "Above current grade level", "Not sure"],
    challenge: "What feels most difficult right now? (optional)",
    challengePlaceholder: "Fractions, homework confidence, reading Armenian, an upcoming exam…",
  },
  preference: {
    title: "What kind of support are you considering?",
    hint: "This helps us recommend the right starting point—it isn’t a commitment.",
    format: "Lesson preference",
    formats: { individual: "Individual lessons", group: "Small-group lessons", choose: "Help me choose" },
    groupNote: "Group availability depends on learners having a compatible level, goal, and schedule.",
    start: "How soon would you like to begin?",
    starts: ["As soon as possible", "Within two weeks", "Within one month", "Flexible", "Just exploring"],
  },
  schedule: {
    title: "When could lessons usually work?",
    hint: "A broad window is enough. We won’t book anything at this stage.",
    timezone: "Time zone",
    timezoneHint: "We’ve filled this from your device. Change it if needed.",
    days: "Preferred days",
    dayOptions: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
    times: "Preferred time ranges",
    timeOptions: ["Morning", "Afternoon", "Evening", "Flexible"],
    flexibility: "Schedule flexibility (optional)",
    flexibilityOptions: ["Dates are fairly fixed", "Some flexibility", "Very flexible"],
    note: "Flexible availability can make tutor or group matching easier.",
  },
  contact: {
    title: "How should we contact you?",
    hint: "Please share parent or guardian details only.",
    name: "Parent or guardian name",
    email: "Email address",
    phone: "Phone number (optional)",
    method: "Preferred contact method",
    methods: { email: "Email", phone: "Phone", either: "Either is fine" },
    more: "Anything else we should know? (optional)",
    moreSummary: "Add a note",
    notesPlaceholder: "A practical detail that would help us prepare…",
    consentPrefix: "I agree to the",
    privacy: "Privacy Policy",
    reassurance: "We use these details only to respond to your request and manage the consultation process.",
  },
  validation: {
    subject: "Choose a subject or select ‘Not sure yet.’",
    goal: "Choose at least one learning goal.",
    grade: "Choose a grade, course, or learning path.",
    format: "Choose a lesson preference.",
    start: "Choose when you would like to begin.",
    timezone: "Enter your time zone.",
    days: "Choose at least one preferred day.",
    times: "Choose at least one preferred time range.",
    name: "Enter the parent or guardian’s name.",
    email: "Enter a valid email address.",
    method: "Choose a preferred contact method.",
    privacy: "Please agree to the Privacy Policy before submitting.",
  },
  review: {
    title: "Review your consultation request",
    hint: "Check the essentials before sending. You can edit any section.",
    subject: "Learning need",
    level: "Learner level",
    format: "Lesson preference",
    schedule: "Preferred schedule",
    contact: "Parent contact",
    submit: "Send consultation request",
    sending: "Sending request…",
    reassurance: "You are not committing to lessons by submitting this request.",
    missing: "Not selected yet",
  },
  panel: {
    eyebrow: "Your consultation note",
    title: "What happens next?",
    next: [
      ["We review your request", "We look at the subject, level, goal, and schedule you shared."],
      ["We contact you", "We discuss the learner’s needs and clarify a useful starting point."],
      ["We recommend a next step", "This may be an assessment, individual tutor match, or group matching request."],
    ],
    summary: "Request summary",
    trust: ["Verified tutor records", "Structured curriculum", "Parent-visible progress", "No pressure to enroll"],
    privacy: "Only consultation details are collected here. Please don’t include sensitive learner information.",
    labels: ["Subject", "Level", "Goal", "Format", "Schedule"],
  },
  error: "We could not send your request. Your information is still here. Please try again.",
  success: {
    eyebrow: "Request received",
    title: "Your consultation request is received.",
    body: "We’ll review the details and contact you to discuss a suitable next step.",
    nextTitle: "What happens next",
    next: ["Request review", "Parent conversation", "Tutor, assessment, or group recommendation"],
    explore: "Explore the selected curriculum",
    how: "Learn how 2tor works",
    home: "Return to homepage",
  },
  trustSection: {
    eyebrow: "Focused by design",
    title: "Your information stays focused on the consultation.",
    items: [
      ["Used only for your request", "We use the details to understand the learner’s needs and contact you."],
      ["No public learner profile", "Consultation information is not displayed publicly."],
      ["Clear deletion policy", "The request record is marked for deletion after 90 days."],
    ],
  },
  faq: {
    eyebrow: "Before you send",
    title: "A few useful answers.",
    items: [
      ["Is the consultation really free?", "Yes. The first consultation is free, and no payment is required to submit this request."],
      ["Do I need to know the learner’s exact level?", "No. Choose “Not sure” and we’ll clarify the starting point together."],
      ["Can you help me choose a lesson format?", "Yes. Select “Help me choose” and we’ll discuss individual and group options."],
      ["What happens after I submit?", "We review the request, contact you, and recommend a suitable next step."],
      ["What if I’m only exploring?", "That’s completely fine. Choose “Just exploring” for your preferred start time."],
    ],
  },
} as const;

const hy = {
  ...en,
  eyebrow: "Անվճար առաջին քայլ",
  title: "Եկեք հասկանանք՝ ինչ է պետք ձեր սովորողին։",
  intro: "Մի փոքր պատմեք սովորողի, նրա նպատակների և ժամանակացույցի մասին։ Մենք կօգնենք ընտրել համապատասխան առարկան, մակարդակը, դասավանդողին և դասի ձևաչափը։",
  assurances: ["Մոտ 2 րոպե", "Վճարում չի պահանջվում", "Առանց պարտավորության", "Միայն ծնողի կամ խնամակալի տվյալներ"],
  stepLabel: (step: number) => `Քայլ ${step}՝ 5-ից`,
  reviewLabel: "Դիտել հարցումը",
  steps: ["Ուսուցման կարիք", "Սովորողի մակարդակ", "Դասի ձևաչափ", "Ժամանակացույց", "Ծնողի տվյալներ"],
  back: "Հետ",
  edit: "Փոփոխել",
  continue: ["Ընտրել սովորողի մակարդակը", "Ընտրել դասի ձևաչափը", "Անցնել ժամանակացույցին", "Ավելացնել ծնողի տվյալները", "Դիտել հարցումը"],
  learning: {
    ...en.learning,
    title: "Ինչի՞ հարցում է պետք աջակցություն։",
    hint: "Ընտրեք ամենամոտ տարբերակը․ հետո կարող եք փոխել։",
    subject: "Առարկա կամ ուսուցման ուղի",
    subjects: { mathematics: "Մաթեմատիկա", armenian: "Հայոց լեզու և մշակույթ", "group-lessons": "Խմբային դասեր", "not-sure": "Դեռ վստահ չեմ" },
    goal: "Ո՞րն է հիմնական նպատակը։",
    goals: { "catch-up": "Լրացնել բացերը", "stay-on-track": "Պահպանել ընթացքը", "move-ahead": "Առաջ անցնել", homework: "Տնային աշխատանքի աջակցություն", "exam-prep": "Պատրաստվել քննության", confidence: "Ամրապնդել վստահությունը", "problem-solving": "Զարգացնել խնդիրների լուծումը", "armenian-connection": "Կապվել հայոց լեզվի և մշակույթի հետ", "not-sure": "Դեռ վստահ չեմ" },
  },
  learner: {
    ...en.learner,
    title: "Պատմեք սովորողի մասին։",
    hint: "Սովորողի անունը կամ ծննդյան ամսաթիվը պետք չէ։",
    grade: "Դասարան, դասընթաց կամ ուսուցման ուղի",
    select: "Ընտրեք տարբերակ",
    mathLevels: ["1-ին դասարան", "2-րդ դասարան", "3-րդ դասարան", "4-րդ դասարան", "5-րդ դասարան", "6-րդ դասարան", "7-րդ դասարան", "8-րդ դասարան", "Նախահանրահաշիվ", "Հանրահաշիվ I", "Երկրաչափություն", "Հանրահաշիվ II", "Նախահաշիվ", "Վստահ չեմ"],
    armenianLevels: ["Լրիվ սկսնակ", "Որոշ չափով հասկանում է հայերեն", "Խոսքի զարգացում", "Կարդալ և գրել", "Քերականություն և ակադեմիական հայերեն", "Հայ մշակույթ և ժառանգություն", "Առաջադեմ հայերեն", "Վստահ չեմ"],
    generalLevels: ["Տարրական դպրոց", "Միջին դպրոց", "Ավագ դպրոց", "Մեծահասակ սովորող", "Վստահ չեմ"],
    currentLevel: "Ընթացիկ մակարդակ (ըստ ցանկության)",
    currentLevels: ["Հիմքային աջակցության կարիք ունի", "Մի փոքր ցածր է ընթացիկ դասարանից", "Ընթացիկ դասարանի մակարդակին է", "Ընթացիկ դասարանից բարձր է", "Վստահ չեմ"],
    challenge: "Ի՞նչն է հիմա ամենադժվարը (ըստ ցանկության)",
    challengePlaceholder: "Կոտորակներ, տնային աշխատանքի վստահություն, հայերեն կարդալ, մոտակա քննություն…",
  },
  preference: {
    ...en.preference,
    title: "Ի՞նչ տեսակի աջակցություն եք դիտարկում։",
    hint: "Սա օգնում է առաջարկել ճիշտ մեկնարկը և պարտավորություն չէ։",
    format: "Դասի նախընտրություն",
    formats: { individual: "Անհատական դասեր", group: "Փոքր խմբով դասեր", choose: "Օգնեք ընտրել" },
    groupNote: "Խմբի առկայությունը կախված է համատեղելի մակարդակ, նպատակ և ժամանակացույց ունեցող սովորողներից։",
    start: "Ե՞րբ կցանկանայիք սկսել։",
    starts: ["Հնարավորինս շուտ", "Երկու շաբաթվա ընթացքում", "Մեկ ամսվա ընթացքում", "Ճկուն", "Պարզապես ուսումնասիրում եմ"],
  },
  schedule: {
    ...en.schedule,
    title: "Ե՞րբ կարող են սովորաբար կայանալ դասերը։",
    hint: "Ընդհանուր ժամանակահատվածը բավարար է․ այս փուլում ոչինչ չենք ամրագրում։",
    timezone: "Ժամային գոտի",
    timezoneHint: "Լրացրել ենք ձեր սարքից․ անհրաժեշտության դեպքում փոխեք։",
    days: "Նախընտրելի օրեր",
    dayOptions: ["Երկուշաբթի", "Երեքշաբթի", "Չորեքշաբթի", "Հինգշաբթի", "Ուրբաթ", "Շաբաթ", "Կիրակի"],
    times: "Նախընտրելի ժամեր",
    timeOptions: ["Առավոտ", "Կեսօրից հետո", "Երեկո", "Ճկուն"],
    flexibility: "Ժամանակացույցի ճկունություն (ըստ ցանկության)",
    flexibilityOptions: ["Ժամերը գրեթե հաստատուն են", "Որոշ չափով ճկուն", "Շատ ճկուն"],
    note: "Ճկուն ժամերը կարող են հեշտացնել դասավանդողի կամ խմբի ընտրությունը։",
  },
  contact: {
    ...en.contact,
    title: "Ինչպե՞ս կապվենք ձեզ հետ։",
    hint: "Նշեք միայն ծնողի կամ խնամակալի տվյալները։",
    name: "Ծնողի կամ խնամակալի անուն",
    email: "Էլ. փոստ",
    phone: "Հեռախոսահամար (ըստ ցանկության)",
    method: "Կապի նախընտրելի եղանակ",
    methods: { email: "Էլ. փոստ", phone: "Հեռախոս", either: "Ցանկացածը" },
    more: "Ուրիշ ի՞նչ պետք է իմանանք (ըստ ցանկության)",
    moreSummary: "Ավելացնել նշում",
    notesPlaceholder: "Գործնական մանրուք, որը կօգնի պատրաստվել…",
    consentPrefix: "Համաձայն եմ",
    privacy: "Գաղտնիության քաղաքականությանը",
    reassurance: "Այս տվյալներն օգտագործում ենք միայն հարցմանը պատասխանելու և խորհրդատվությունը կազմակերպելու համար։",
  },
  validation: {
    subject: "Ընտրեք առարկա կամ «Դեռ վստահ չեմ»։", goal: "Ընտրեք առնվազն մեկ ուսուցման նպատակ։", grade: "Ընտրեք դասարան, դասընթաց կամ ուսուցման ուղի։", format: "Ընտրեք դասի նախընտրություն։", start: "Ընտրեք՝ երբ եք ցանկանում սկսել։", timezone: "Նշեք ժամային գոտին։", days: "Ընտրեք առնվազն մեկ նախընտրելի օր։", times: "Ընտրեք առնվազն մեկ նախընտրելի ժամ։", name: "Նշեք ծնողի կամ խնամակալի անունը։", email: "Նշեք վավեր էլ. հասցե։", method: "Ընտրեք կապի նախընտրելի եղանակ։", privacy: "Ուղարկելուց առաջ համաձայնեք Գաղտնիության քաղաքականությանը։",
  },
  review: {
    ...en.review,
    title: "Դիտեք խորհրդատվության հարցումը",
    hint: "Ուղարկելուց առաջ ստուգեք հիմնականը։ Յուրաքանչյուր բաժին կարող եք փոխել։",
    subject: "Ուսուցման կարիք", level: "Սովորողի մակարդակ", format: "Դասի նախընտրություն", schedule: "Նախընտրելի ժամանակացույց", contact: "Ծնողի կապ", submit: "Ուղարկել խորհրդատվության հարցումը", sending: "Ուղարկվում է…", reassurance: "Հարցումն ուղարկելով՝ դուք դասերի պարտավորություն չեք ստանձնում։", missing: "Դեռ ընտրված չէ",
  },
  panel: {
    ...en.panel,
    eyebrow: "Ձեր խորհրդատվության նշումը",
    title: "Ի՞նչ կլինի հետո։",
    next: [["Մենք դիտարկում ենք հարցումը", "Դիտարկում ենք նշված առարկան, մակարդակը, նպատակը և ժամանակացույցը։"], ["Կապվում ենք ձեզ հետ", "Քննարկում ենք սովորողի կարիքները և հստակեցնում օգտակար մեկնարկը։"], ["Առաջարկում ենք հաջորդ քայլը", "Դա կարող է լինել գնահատում, անհատական դասավանդողի ընտրություն կամ խմբի հարցում։"]],
    summary: "Հարցման ամփոփում",
    trust: ["Ստուգված դասավանդողների գրառումներ", "Կառուցվածքային ուսումնական ծրագիր", "Ծնողին տեսանելի առաջընթաց", "Առանց գրանցման ճնշման"],
    privacy: "Այստեղ հավաքվում են միայն խորհրդատվության տվյալներ։ Մի ներառեք սովորողի զգայուն տեղեկություններ։",
    labels: ["Առարկա", "Մակարդակ", "Նպատակ", "Ձևաչափ", "Ժամանակացույց"],
  },
  error: "Չհաջողվեց ուղարկել հարցումը։ Ձեր տվյալները պահպանվել են այստեղ։ Փորձեք կրկին։",
  success: {
    ...en.success,
    eyebrow: "Հարցումը ստացվել է", title: "Ձեր խորհրդատվության հարցումը ստացվել է։", body: "Կդիտարկենք տվյալները և կկապվենք՝ համապատասխան հաջորդ քայլը քննարկելու համար։", nextTitle: "Ի՞նչ կլինի հետո", next: ["Հարցման դիտարկում", "Զրույց ծնողի հետ", "Դասավանդողի, գնահատման կամ խմբի առաջարկ"], explore: "Դիտել ընտրված ուսումնական ծրագիրը", how: "Ինչպես է աշխատում 2tor-ը", home: "Վերադառնալ գլխավոր էջ",
  },
  trustSection: {
    eyebrow: "Նպատակային մոտեցում", title: "Ձեր տվյալները մնում են խորհրդատվության շրջանակում։", items: [["Միայն ձեր հարցման համար", "Տվյալներն օգտագործում ենք սովորողի կարիքը հասկանալու և ձեզ հետ կապվելու համար։"], ["Առանց սովորողի հանրային պրոֆիլի", "Խորհրդատվության տվյալները հանրայնորեն չեն ցուցադրվում։"], ["Հստակ ջնջման քաղաքականություն", "Հարցման գրառումը նշվում է 90 օր հետո ջնջելու համար։"]],
  },
  faq: {
    eyebrow: "Ուղարկելուց առաջ", title: "Մի քանի օգտակար պատասխան։", items: [["Խորհրդատվությունն իսկապե՞ս անվճար է։", "Այո։ Առաջին խորհրդատվությունն անվճար է, և հարցումն ուղարկելու համար վճարում չի պահանջվում։"], ["Պե՞տք է իմանամ սովորողի ճշգրիտ մակարդակը։", "Ոչ։ Ընտրեք «Վստահ չեմ», և միասին կհստակեցնենք մեկնարկը։"], ["Կօգնե՞ք ընտրել դասի ձևաչափը։", "Այո։ Ընտրեք «Օգնեք ընտրել», և կքննարկենք անհատական ու խմբային տարբերակները։"], ["Ի՞նչ կլինի ուղարկելուց հետո։", "Կդիտարկենք հարցումը, կկապվենք և կառաջարկենք համապատասխան հաջորդ քայլ։"], ["Իսկ եթե պարզապես ուսումնասիրում եմ։", "Դա լիովին ընդունելի է։ Սկսելու ժամկետի համար ընտրեք «Պարզապես ուսումնասիրում եմ»։"]],
  },
};

export function consultationContent(locale: Locale) {
  return locale === "hy" ? hy : en;
}

export type ConsultationContent = typeof en;
